@extends('layouts.app')
@section('content')
@php
 $money = fn($v) => 'AED '.number_format((float)$v,2);
 $depositInvoices = $booking->invoices->filter(fn($i) => (float)(($i->fees ?? [])['Security Deposit'] ?? 0)>0);
 $openRequest = $refunds->first(fn($r) => in_array($r->status,['pending','approved']));
@endphp
<h4>Security Deposit Wallet</h4><p>{{ $booking->booking_reference }} · {{ $booking->guest_name }} · {{ $booking->property?->building?->name }} — {{ $booking->property?->name }}</p>
<nav class="nav nav-pills gap-2 mb-3"><a class="nav-link" href="{{ route('admin.booking.show',$booking) }}">Booking & Invoices</a><a class="nav-link active" href="{{ route('admin.booking.deposit-wallet',$booking) }}">Security Deposit</a></nav>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row g-3 mb-3">@foreach(['received'=>'Received','carry_in'=>'Carried In','deducted'=>'Deductions','refunded'=>'Actually Refunded','carry_out'=>'Carried Out','held'=>'Currently Held'] as $key=>$label)<div class="col-md-4 col-xl-2"><div class="card mb-0"><div class="card-body"><small>{{ $label }}</small><h5>{{ $money($totals[$key]) }}</h5></div></div></div>@endforeach</div>
<div class="alert alert-info">A deposit charge is not proof of receipt. Allocate a recorded payment or record a new payment below. Never collect an already-paid deposit again. Deposits are separate from rental income.</div>
<p class="text-muted">Deposit charges on these invoices: <strong>{{ $money($depositInvoices->sum(fn($i) => (float)(($i->fees ?? [])['Security Deposit'] ?? 0))) }}</strong> · Not yet allocated from receipts: <strong>{{ $money(max(0,$depositInvoices->sum(fn($i) => (float)(($i->fees ?? [])['Security Deposit'] ?? 0))-$totals['received'])) }}</strong></p>
<div class="row"><div class="col-xl-6"><div class="card"><div class="card-header"><h5>Allocate Existing Payment</h5></div><div class="card-body">
<form method="POST" action="{{ route('admin.booking.deposit.allocate',$booking) }}">@csrf<input type="hidden" name="submission_id" value="{{ (string)\Illuminate\Support\Str::uuid() }}">
<label>Recorded payment</label><select name="payment_id" class="form-select mb-2" required><option value="">Select payment</option>@foreach($depositInvoices as $invoice)@foreach($invoice->payments as $payment)@if((float)$payment->amount>(float)($allocations[$payment->id]??0))<option value="{{ $payment->id }}">{{ $invoice->invoice_number }} · {{ $payment->payment_date?->format('d M Y') }} · Paid {{ $money($payment->amount) }} · Deposit allocated {{ $money($allocations[$payment->id]??0) }}</option>@endif @endforeach @endforeach</select>
<label>Deposit portion (AED)</label><input type="number" name="amount" class="form-control mb-3" min="0.01" step="0.01" required><button class="btn btn-primary">Allocate — No New Collection</button><p class="small text-muted mt-2">Legacy “Paid” invoices without an itemised ledger payment must be reconciled before refunding.</p></form></div></div></div>
<div class="col-xl-6"><div class="card"><div class="card-header"><h5>Record New Deposit Payment</h5></div><div class="card-body"><form method="POST" action="{{ route('admin.booking.deposit.collect',$booking) }}" enctype="multipart/form-data">@csrf
<input type="hidden" name="submission_id" value="{{ (string)\Illuminate\Support\Str::uuid() }}">
<label>Unpaid invoice</label><select name="invoice_id" class="form-select mb-2" required><option value="">Select invoice</option>@foreach($depositInvoices as $invoice)@if($invoice->balance_due>0)<option value="{{ $invoice->id }}">{{ $invoice->invoice_number }} · Balance {{ $money($invoice->balance_due) }}</option>@endif @endforeach</select>
<div class="row g-2"><div class="col-6"><label>Amount (AED)</label><input type="number" name="amount" min="0.01" step="0.01" class="form-control" required></div><div class="col-6"><label>Date</label><input type="date" name="payment_date" value="{{ today()->toDateString() }}" class="form-control" required></div><div class="col-6"><label>Received Into</label><select name="bank_account_id" class="form-select" required><option value="">Select account</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select></div><div class="col-6"><label>Method</label><select name="payment_method" class="form-select"><option>Bank Transfer</option><option>Cash</option><option>Card</option><option>Cheque</option></select></div><div class="col-6"><label>Reference</label><input name="reference" class="form-control" required></div><div class="col-6"><label>Receipt</label><input type="file" name="receipt" class="form-control" accept=".pdf,.jpg,.jpeg,.png" required></div></div><button class="btn btn-success mt-3">Record Actual Deposit Received</button></form></div></div></div></div>
<div class="row"><div class="col-xl-8"><div class="card"><div class="card-header"><h5>Request Refund</h5></div><div class="card-body">
@if($openRequest)<p class="text-warning">{{ $openRequest->request_no }} is {{ $openRequest->status }}. Complete it first.</p>@elseif($totals['held']<=0)<p>No deposit currently held.</p>@else
<form method="POST" action="{{ route('admin.booking.deposit.request',$booking) }}" enctype="multipart/form-data">@csrf
<label>Inspection (optional)</label><select name="inspection_id" class="form-select mb-2"><option value="">No inspection linked</option>@foreach($booking->inspections as $inspection)<option value="{{ $inspection->id }}">{{ $inspection->inspection_number }} · {{ $inspection->type_label }}</option>@endforeach</select><label>Reason / Notes</label><textarea name="reason" class="form-control mb-3" minlength="5" required></textarea><h6>Deductions — leave empty for full refund</h6><div id="deductionRows"></div><button type="button" id="addDeduction" class="btn btn-sm btn-outline-primary mb-2">+ Add Deduction</button><div class="alert alert-light border">Held {{ $money($totals['held']) }} · Proposed deductions <strong id="deductionTotal">AED 0.00</strong> · Proposed refund <strong id="refundPreview">{{ $money($totals['held']) }}</strong></div><p class="small text-muted">Deductions require evidence. Approved deductions remain in a holding account pending final account allocation. Approval does not transfer money.</p><button class="btn btn-primary">Submit for Admin Approval</button></form>@endif
</div></div></div><div class="col-xl-4"><div class="card"><div class="card-header"><h5>Carry Forward to Renewal</h5></div><div class="card-body"><p>Same guest and unit only. Set the renewal's Security Deposit to 0 before carrying existing funds. No new collection or cash movement.</p>
@if(!$openRequest && $totals['held']>0 && $booking->renewals->isNotEmpty())<form method="POST" action="{{ route('admin.booking.deposit.carry',$booking) }}">@csrf<input type="hidden" name="submission_id" value="{{ (string)\Illuminate\Support\Str::uuid() }}"><label>Linked renewal</label><select name="target_id" class="form-select mb-2" required>@foreach($booking->renewals as $renewal)<option value="{{ $renewal->id }}">{{ $renewal->booking_reference }}</option>@endforeach</select><label>Amount (AED)</label><input type="number" name="amount" min="0.01" step="0.01" max="{{ $totals['held'] }}" value="{{ $totals['held'] }}" class="form-control mb-2" required><button class="btn btn-outline-primary">Carry Forward</button></form>@else<p class="text-muted">Requires held funds, a linked renewal, and no open refund.</p>@endif</div></div></div></div>
<div class="card"><div class="card-header"><h5>Refund Requests, Approval & Payment</h5></div><div class="card-body">
@forelse($refunds as $refund)<div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between"><h5>{{ $refund->request_no }}</h5><span class="badge {{ $refund->status==='settled'?'bg-success':($refund->status==='rejected'?'bg-danger':'bg-warning') }}">{{ ucfirst($refund->status) }}</span></div><p class="small text-muted">Requested by {{ $refund->requester?->name }} · {{ $refund->created_at?->format('d M Y H:i') }} @if($refund->reviewed_at) · Reviewed by {{ $refund->reviewer?->name }} · {{ $refund->reviewed_at->format('d M Y H:i') }} @endif</p><p>{{ $refund->reason }}</p><p>Deposit {{ $money($refund->held_at_request) }} · Deductions {{ $money($refund->deduction_amount) }} · Refund {{ $money($refund->refund_amount) }} · Actually paid {{ $money($refund->paid_amount) }}</p>
@if($refund->inspection)<a href="{{ route('admin.inspection.show',$refund->inspection) }}">View Inspection</a>@endif
@foreach($refund->deductions??[] as $deduction)<p class="small mb-1">{{ $deduction['description'] }} — {{ $money($deduction['amount']) }} <a href="{{ \App\Support\MediaStorage::url($deduction['evidence']??null) }}" target="_blank" rel="noopener">Evidence</a></p>@endforeach
@if($refund->review_notes)<p>Review notes: {{ $refund->review_notes }}</p>@endif
@if($refund->status==='pending')<form method="POST" action="{{ route('admin.booking.deposit.review',[$booking,$refund]) }}">@csrf<label>Admin Review Notes</label><textarea name="review_notes" class="form-control mb-2" minlength="3" required></textarea><button name="decision" value="rejected" class="btn btn-outline-danger">Reject</button> <button name="decision" value="approved" class="btn btn-success">Approve — No Cash Movement</button></form>
@elseif($refund->status==='approved')<details><summary class="text-primary fw-semibold">Record Actual Refund · Remaining {{ $money($refund->remaining_amount) }}</summary><form class="mt-3" method="POST" action="{{ route('admin.booking.deposit.pay',[$booking,$refund]) }}" enctype="multipart/form-data">@csrf<input type="hidden" name="submission_id" value="{{ (string)\Illuminate\Support\Str::uuid() }}"><div class="row g-2"><div class="col-md-4"><label>Amount (AED)</label><input type="number" name="amount" step="0.01" min="0.01" max="{{ $refund->remaining_amount }}" value="{{ $refund->remaining_amount }}" class="form-control" required></div><div class="col-md-4"><label>Refund Date</label><input type="date" name="entry_date" min="{{ $refund->reviewed_at?->toDateString() }}" max="{{ today()->toDateString() }}" value="{{ today()->toDateString() }}" class="form-control" required></div><div class="col-md-4"><label>Pay From</label><select name="bank_account_id" class="form-select" required><option value="">Select account</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select></div><div class="col-md-4"><label>Recipient</label><input name="recipient" value="{{ $booking->guest_name }}" class="form-control" required></div><div class="col-md-4"><label>Method</label><select name="payment_method" class="form-select"><option>Bank Transfer</option><option>Cash</option><option>Card</option><option>Cheque</option></select></div><div class="col-md-4"><label>Transfer / Receipt Reference</label><input name="reference" class="form-control" required></div><div class="col-md-6"><label>Proof of Actual Payment</label><input type="file" name="proof" class="form-control" accept=".pdf,.jpg,.jpeg,.png" required></div><div class="col-md-6"><label>Notes</label><input name="notes" class="form-control"></div></div><p class="small text-muted mt-2">Partial refunds supported. This records a payment already made; it does not send a bank transfer.</p><button class="btn btn-primary">Confirm Refund Paid</button></form></details>@endif</div>
@empty<p>No refund requests.</p>@endforelse</div></div>
<div class="card"><div class="card-header"><h5>Deposit History & Refund Receipts</h5></div><div class="table-responsive"><table class="table"><thead><tr><th>Date</th><th>Activity</th><th>Amount</th><th>Account / Reference</th><th>Recorded By</th><th>Documents</th></tr></thead><tbody>
@forelse($entries as $entry)<tr><td>{{ $entry->entry_date?->format('d M Y') }}</td><td>{{ ucfirst(str_replace('_',' ',$entry->kind)) }}<div class="small">{{ $entry->notes }}</div>@if($entry->relatedBooking)<a href="{{ route('admin.booking.deposit-wallet',$entry->relatedBooking) }}">{{ $entry->relatedBooking->booking_reference }}</a>@endif</td><td>{{ $money($entry->amount) }}</td><td>{{ $entry->bankAccount?->name??'No cash movement' }}<br>{{ $entry->reference }}</td><td>{{ $entry->creator?->name??'System' }}</td><td>@if($entry->receipt_path)<a class="btn btn-sm btn-light" href="{{ \App\Support\MediaStorage::url($entry->receipt_path) }}" target="_blank" rel="noopener">Proof</a>@endif @if($entry->kind==='refunded')<a class="btn btn-sm btn-outline-primary" href="{{ route('admin.booking.deposit.receipt',[$booking,$entry]) }}">Refund Receipt PDF</a>@endif</td></tr>@empty<tr><td colspan="6">No deposit movements.</td></tr>@endforelse</tbody></table></div></div>
@endsection
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){
 const rows=document.getElementById('deductionRows'),add=document.getElementById('addDeduction');if(!rows||!add)return;let next=0;
 const calculate=()=>{let total=0;rows.querySelectorAll('[data-amount]').forEach(i=>total+=Number(i.value||0));const fmt=n=>'AED '+n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});document.getElementById('deductionTotal').textContent=fmt(total);document.getElementById('refundPreview').textContent=fmt(@json((float)$totals['held'])-total);};
 add.addEventListener('click',()=>{if(rows.children.length>=20)return;const n=next++,row=document.createElement('div');row.className='row g-2 border rounded p-2 mb-2';row.innerHTML=`<div class="col-md-5"><label>Reason</label><input name="deductions[${n}][description]" class="form-control" required></div><div class="col-md-2"><label>AED</label><input name="deductions[${n}][amount]" type="number" min="0.01" step="0.01" class="form-control" data-amount required></div><div class="col-md-4"><label>Evidence</label><input name="deductions[${n}][evidence]" type="file" accept=".pdf,.jpg,.jpeg,.png" class="form-control" required></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger" aria-label="Remove deduction">×</button></div>`;row.querySelector('button').addEventListener('click',()=>{row.remove();calculate();});rows.appendChild(row);});rows.addEventListener('input',calculate);
});
</script>
@endpush
