@extends('layouts.app')
@section('title', 'Email Delivery Log')
@section('content')
<div class="container-fluid">
<div class="d-flex justify-content-between align-items-start mb-3"><div><h3 class="mb-1">Email Delivery Log</h3><p class="text-muted mb-0">Track owner statements, recipients and delivery results.</p></div><div class="d-flex gap-2">@foreach(['queued','sent','failed'] as $value)<span class="badge {{ $value==='sent'?'bg-success':($value==='failed'?'bg-danger':'bg-warning') }}">{{ ucfirst($value) }} {{ \App\Models\EmailDelivery::where('status',$value)->count() }}</span>@endforeach</div></div>
<div class="card"><div class="card-body border-bottom"><form class="row g-2"><div class="col-md-7"><input class="form-control" name="search" value="{{ $search }}" placeholder="Search owner, unit, recipient, subject or purpose"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">All statuses</option>@foreach(['queued','sent','failed'] as $value)<option value="{{ $value }}" @selected($status===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-primary w-100">Filter</button></div></form></div>
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Date / Status</th><th>Recipients</th><th>Owner</th><th>Unit / Building</th><th>Purpose / Subject</th><th>Requested By</th></tr></thead><tbody>
@forelse($deliveries as $delivery)<tr><td><div>{{ ($delivery->sent_at ?? $delivery->failed_at ?? $delivery->queued_at)?->timezone('Asia/Dubai')->format('d M Y H:i') }}</div><span class="badge {{ $delivery->status==='sent'?'bg-success':($delivery->status==='failed'?'bg-danger':'bg-warning') }}">{{ ucfirst($delivery->status) }}</span>@if($delivery->failure_reason)<div class="small text-danger mt-1" title="{{ $delivery->failure_reason }}">{{ \Illuminate\Support\Str::limit($delivery->failure_reason,60) }}</div>@endif</td><td>@foreach($delivery->recipients as $email)<div class="small text-break"><i class="ri-mail-line me-1"></i>{{ $email }}</div>@endforeach</td><td>{{ $delivery->landlord?->name ?? '—' }}</td><td><strong>{{ $delivery->property?->name ?? 'All units' }}</strong><div class="small text-muted">{{ $delivery->property?->building?->building_name ?? '—' }}</div></td><td><strong>{{ $delivery->purpose ?? '—' }}</strong><div class="small text-muted">{{ $delivery->subject }}</div></td><td>{{ $delivery->creator?->name ?? 'System' }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-5">No email deliveries found.</td></tr>@endforelse
</tbody></table></div>@if($deliveries->hasPages())<div class="card-footer">{{ $deliveries->links('pagination::bootstrap-5') }}</div>@endif</div></div>
@endsection
