@extends('layouts.app')
@section('content')
@include('admin.accounting.partials.module-nav')
<div class="d-flex justify-content-between align-items-center"><h4>Bank Reconciliation</h4><a href="{{ route('admin.accounting.bank-reconciliation.system-transactions') }}" class="btn btn-outline-primary">System transactions & references</a></div>
<p class="text-muted">Upload a Wio or ADCB CSV/Excel statement and match each bank transaction against a recorded accounting entry.</p>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card mb-4"><div class="card-header"><h5 class="mb-0">Upload statement</h5></div><div class="card-body"><form method="post" action="{{ route('admin.accounting.bank-reconciliation.upload') }}" enctype="multipart/form-data" class="row g-3 align-items-end">@csrf
<div class="col-md-3"><label class="form-label">Bank</label><select name="bank" class="form-select" required><option value="">Select bank</option><option value="wio" @selected(old('bank')==='wio')>Wio</option><option value="adcb" @selected(old('bank')==='adcb')>ADCB</option></select></div>
<div class="col-md-4"><label class="form-label">Bank account</label><select name="bank_account_id" class="form-select" required><option value="">Select account</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(old('bank_account_id')===$account->id)>{{ $account->name }} ({{ $account->currency }})</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Bank statement</label><input type="file" name="statement" class="form-control" accept=".csv,text/csv,.txt,.xls,.xlsx,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required></div>
<div class="col-md-2"><button class="btn btn-primary w-100">Upload</button></div></form><p class="small text-muted mt-3 mb-0">ADCB Excel exports are supported directly. CSV files must include a date, reference, and debit/credit or signed amount. Up to 10,000 rows. Importing does not post money to the ledger.</p></div></div>
<div class="card"><div class="card-header"><h5 class="mb-0">Imported statements</h5></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Uploaded</th><th>Bank</th><th>Account</th><th>File</th><th>Confirmed</th><th></th></tr></thead><tbody>@forelse($imports as $import)<tr><td>{{ $import->created_at->format('d M Y H:i') }}</td><td>{{ strtoupper($import->bank) }}</td><td>{{ $import->account?->name }}</td><td>{{ $import->filename }}</td><td>{{ $import->confirmed_count }} / {{ $import->transactions_count }}</td><td><a class="btn btn-sm btn-primary" href="{{ route('admin.accounting.bank-reconciliation.show',$import) }}">Review</a></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">No bank statements uploaded yet.</td></tr>@endforelse</tbody></table></div><div class="card-body">{{ $imports->links() }}</div></div>
@endsection
