@extends('layouts.app')
@section('content')
@include('admin.accounting.partials.module-nav')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4>{{ strtoupper($import->bank) }} Statement Review</h4><p class="text-muted mb-0">{{ $import->account?->name }} · {{ $import->filename }}</p></div><div class="d-flex gap-2"><form method="post" action="{{ route('admin.accounting.bank-reconciliation.confirm-all', $import) }}">@csrf<button class="btn btn-success">Match all unique transactions</button></form><a href="{{ route('admin.accounting.bank-reconciliation') }}" class="btn btn-light">All imports</a></div></div>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="alert alert-info">Only a matching account, reference, direction, and exact amount can be confirmed. Rows without a unique match remain open for review.</div>
<div class="card"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Row / Date</th><th>Bank reference</th><th>Description</th><th class="text-end">Debit</th><th class="text-end">Credit</th><th>Status / Recorded entry</th><th>Match comment</th></tr></thead><tbody>
@foreach($transactions as $transaction)<tr><td>#{{ $transaction->row_number }}<br>{{ $transaction->transaction_date->format('d M Y') }}</td><td>{{ $transaction->reference ?: '—' }}</td><td>{{ $transaction->description ?: '—' }}</td><td class="text-end">{{ (float)$transaction->debit>0?number_format((float)$transaction->debit,2):'—' }}</td><td class="text-end">{{ (float)$transaction->credit>0?number_format((float)$transaction->credit,2):'—' }}</td><td>@if($transaction->status==='confirmed')<span class="badge bg-success">Confirmed</span><div class="small">{{ $transaction->entry?->entry_no }}</div>@else
@php($matches=$suggestions[$transaction->id] ?? collect())
@if($matches->count()===1)<form method="post" action="{{ route('admin.accounting.bank-reconciliation.confirm',$transaction) }}">@csrf<input type="hidden" name="accounting_entry_id" value="{{ $matches->first()->id }}"><div class="small mb-1">{{ $matches->first()->entry_no }} · {{ $matches->first()->entry_date?->format('d M Y') }}</div><button class="btn btn-sm btn-outline-success">Confirm match</button></form>
@elseif($matches->count()>1)<span class="badge bg-warning text-dark">{{ $matches->count() }} possible entries</span><div class="small text-muted">Resolve duplicate references before confirmation.</div>
@else<span class="badge bg-secondary">Unmatched</span>@endif @endif</td><td class="small">@if($transaction->status==='confirmed')<span class="text-success">Exact reference, direction and amount confirmed.</span>@elseif($matches->count()===1)<span class="text-success">One exact match found. Ready to confirm.</span>@elseif($matches->count()>1)<span class="text-warning">More than one ledger entry has this reference and amount.</span>@elseif(!$transaction->reference)<span class="text-muted">Bank reference is missing.</span>@else<span class="text-muted">No exact ledger match for this reference and amount.</span>@endif</td></tr>@endforeach
</tbody></table></div><div class="card-body">{{ $transactions->links() }}</div></div>
@endsection
