@extends('layouts.app')
@section('content')
@include('admin.accounting.partials.module-nav')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4>System Transactions & References</h4><p class="text-muted mb-0">Recorded software transactions available for bank-statement matching.</p></div><div class="d-flex gap-2"><a href="{{ route('admin.accounting.bank-reconciliation.system-transactions.export', request()->query()) }}" class="btn btn-success">Export CSV</a><a href="{{ route('admin.accounting.bank-reconciliation') }}" class="btn btn-light">Bank reconciliation</a></div></div>
<div class="card mb-3"><div class="card-body"><form method="get" class="row g-3 align-items-end">
<div class="col-lg-3"><label class="form-label">Search reference, booking, guest or purpose</label><input name="search" value="{{ request('search') }}" class="form-control" placeholder="Reference number"></div>
<div class="col-lg-2"><label class="form-label">Bank account</label><select name="bank_account_id" class="form-select"><option value="">All bank accounts</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(request('bank_account_id')==$account->id)>{{ $account->name }}</option>@endforeach</select></div>
<div class="col-lg-2"><label class="form-label">From</label><input type="date" name="from" value="{{ request('from') }}" class="form-control"></div>
<div class="col-lg-2"><label class="form-label">To</label><input type="date" name="to" value="{{ request('to') }}" class="form-control"></div>
<div class="col-lg-2"><label class="form-label">Bank match</label><select name="match_status" class="form-select"><option value="">All</option><option value="matched" @selected(request('match_status')==='matched')>Matched</option><option value="unmatched" @selected(request('match_status')==='unmatched')>Not matched</option></select></div>
<div class="col-lg-1"><button class="btn btn-primary w-100">Apply</button></div>
</form></div></div>
<div class="alert alert-info">Reference No is the value used for exact bank matching. Purpose, category, booking, guest and unit explain where the transaction was used.</div>
<div class="card"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Date / Entry</th><th>Reference No</th><th>Purpose / Description</th><th>Booking / Guest</th><th>Unit</th><th>Bank account</th><th class="text-end">Debit</th><th class="text-end">Credit</th><th>Match</th></tr></thead><tbody>
@forelse($entries as $entry)<tr><td>{{ $entry->entry_date?->format('d M Y') }}<div class="small text-muted">{{ $entry->entry_no }}</div></td><td><strong>{{ $entry->transaction_reference ?: $entry->bankTransfer?->reference ?: '—' }}</strong></td><td><span class="badge bg-light text-dark">{{ \App\Models\AccountingEntry::TYPES[$entry->type] ?? ucfirst($entry->type) }}</span> <span class="small text-muted">{{ $entry->category }}</span><div class="small mt-1">{{ $entry->description }}</div></td><td>@if($entry->booking)<a href="{{ route('admin.booking.show',$entry->booking) }}">{{ $entry->booking->booking_reference }}</a><div class="small">{{ $entry->booking->guest_name }}</div>@else—@endif</td><td>{{ $entry->property?->name ?? $entry->booking?->property?->name ?? '—' }}@if($entry->booking?->property?->building)<div class="small text-muted">{{ $entry->booking->property->building->name ?? $entry->booking->property->building->building_name }}</div>@endif</td><td>{{ $entry->paidFromAccount?->name ?? '—' }}</td><td class="text-end">{{ (float)$entry->debit>0?number_format((float)$entry->debit,2):'—' }}</td><td class="text-end">{{ (float)$entry->credit>0?number_format((float)$entry->credit,2):'—' }}</td><td>@if($entry->bankStatementTransaction)<span class="badge bg-success">Matched</span><div class="small text-muted">{{ strtoupper($entry->bankStatementTransaction->import?->bank) }}</div>@else<span class="badge bg-secondary">Not matched</span>@endif</td></tr>
@empty<tr><td colspan="9" class="text-center text-muted py-4">No software transactions match these filters.</td></tr>@endforelse
</tbody></table></div><div class="card-body">{{ $entries->links() }}</div></div>
@endsection
