@if(\Illuminate\Support\Facades\Route::has('admin.inventory.assess') && $inventoryReview?->status === 'approved' && $inspection->type === 'check_out' && $inspection->booking_id)
<div class="card"><div class="card-body d-flex flex-wrap justify-content-between align-items-center gap-2"><div><h5 class="mb-1">Damage assessment</h5><small class="text-muted">Review estimates, adjust repair/replacement amounts and propose a deduction.</small></div><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#damageAssessment">Assess damage</button><a class="btn btn-light" href="{{ route('admin.booking.deposit-wallet',$inspection->booking_id) }}">Deposit approvals & history</a></div></div>
<div class="modal fade" id="damageAssessment" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><form class="modal-content" method="POST" enctype="multipart/form-data" action="{{ route('admin.inventory.assess',$inspection) }}">@csrf
<div class="modal-header"><div><h5 class="modal-title">Damage assessment — {{ $inspection->inspection_number }}</h5><small>Amounts are proposed only. Separate deposit approval is required.</small></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div>
<div class="modal-body"><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Item</th><th>New missing / damaged</th><th>Estimate AED</th><th>Proposed AED</th><th>Reason / adjustment</th><th>Evidence</th></tr></thead><tbody>
@foreach($inventoryRows as $row)@if(isset($row['estimate']) && ($row['new_missing']+$row['new_damaged']) > 0)
<tr><td>{{ $row['room'] }}<br><strong>{{ $row['name'] }}</strong></td><td>{{ $row['new_missing'] }} / {{ $row['new_damaged'] }}</td><td>{{ number_format($row['estimate'],2) }}</td><td><input aria-label="Proposed charge for {{ $row['name'] }}" class="form-control form-control-sm" style="min-width:100px" name="charges[{{ $row['id'] }}][amount]" type="number" min="0" max="999999" step="0.01" value="{{ $row['estimate'] }}" required></td><td><input class="form-control form-control-sm" name="charges[{{ $row['id'] }}][reason]" aria-label="Reason for {{ $row['name'] }}" placeholder="Repair / replacement reason" maxlength="500"></td><td><input class="form-control form-control-sm" name="charges[{{ $row['id'] }}][evidence]" aria-label="Evidence for {{ $row['name'] }}" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp"></td></tr>
@endif @endforeach</tbody></table></div><p class="small text-muted">Zero excludes an item. Every positive charge needs evidence and a reason. No approved baseline means no eligible charge. Review pre-existing damage and stock movements before proposing.</p><label class="w-100">Assessment notes<textarea name="reason" class="form-control" minlength="5" maxlength="2000" required></textarea></label></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Propose deduction for approval</button></div></form></div></div>
@endif
