@extends('layouts.app')
@section('content')
@php($screen = in_array(request('screen'), ['apartments','unit','templates','history']) ? request('screen') : 'unit')
<ul class="nav nav-tabs mb-3">@foreach(['apartments'=>'All Apartments','unit'=>'Unit Inventory','templates'=>'Items & Templates','history'=>'Tasks & History'] as $key=>$label)<li class="nav-item"><a class="nav-link {{ $screen === $key ? 'active' : '' }}" href="{{ route('admin.inventory.index',['property_id'=>$property?->id,'screen'=>$key]) }}">{{ $label }}</a></li>@endforeach</ul>
<div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3"><div><h4 class="mb-1">Unit Inventory</h4><span class="text-muted">Requirements, actual stock and approved inspection counts</span></div><a class="btn btn-outline-primary btn-sm" href="{{ route('admin.inspection.index') }}">Inspections</a></div>
<div class="card"><div class="card-body d-flex flex-wrap gap-2 justify-content-between">
<form method="GET" class="d-flex gap-2"><input type="hidden" name="screen" value="{{ $screen }}"><label class="visually-hidden" for="inventory-unit">Apartment</label><select id="inventory-unit" name="property_id" class="form-select" onchange="this.form.submit()">@foreach($properties as $unit)<option value="{{ $unit->id }}" @selected($property?->id === $unit->id)>{{ $unit->building?->building_name ?? 'No building' }} — {{ $unit->name }}</option>@endforeach</select><button class="btn btn-light">Open</button></form>
@if($property)<div class="d-flex gap-2"><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#addInventory">Add item</button><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#requestInspection">Request inspection</button></div>@endif
</div></div>
@if($property)
@if($screen === 'apartments')
<div class="card"><div class="card-header">All apartments — inventory balances</div><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Building / Unit</th><th>Required</th><th>Present</th><th>Missing</th><th>Damaged</th><th>Readiness</th><th></th></tr></thead><tbody>@foreach($properties as $unit)@php($summary = $summaries->get($unit->id))<tr><td>{{ $unit->building?->building_name }} — {{ $unit->name }}</td><td>{{ $summary?->required_total ?? 'Not set up' }}</td><td>{{ $summary?->present_total ?? '—' }}</td><td>{{ $summary?->missing_total ?? '—' }}</td><td>{{ $summary?->damaged_total ?? '—' }}</td><td><span class="badge {{ !$summary ? 'bg-secondary' : (($summary->missing_total || $summary->damaged_total) ? 'bg-warning' : 'bg-success') }}">{{ !$summary ? 'Not set up' : (($summary->missing_total || $summary->damaged_total) ? 'Needs attention' : 'Stock complete') }}</span></td><td><a href="{{ route('admin.inventory.index',['property_id' => $unit->id, 'screen'=>'unit']) }}" class="btn btn-light btn-sm">Open</a></td></tr>@endforeach</tbody></table></div></div>
@endif
@if($screen === 'templates')
<div class="card"><div class="card-header">Templates — reuse required items across apartments</div><div class="card-body row g-3"><form class="col-md-6 d-flex gap-2" method="POST" action="{{ route('admin.inventory.template') }}">@csrf<input type="hidden" name="property_id" value="{{ $property->id }}"><input type="hidden" name="action" value="save"><input name="name" class="form-control" aria-label="Template name" placeholder="Save this unit's requirements as e.g. 1 BHK" maxlength="100" required><button class="btn btn-outline-primary">Save template</button></form><form class="col-md-6 d-flex gap-2" method="POST" action="{{ route('admin.inventory.template') }}">@csrf<input type="hidden" name="property_id" value="{{ $property->id }}"><input type="hidden" name="action" value="apply"><select name="template_id" class="form-select" aria-label="Apply template" required><option value="">Select template</option>@foreach($templates as $template)<option value="{{ $template->id }}">{{ $template->name }}</option>@endforeach</select><button class="btn btn-outline-primary">Apply</button></form><small class="text-muted">Adds missing item requirements only. Existing requirements and actual stock are never overwritten.</small></div></div>
@include('admin.inspections.template-editors')
@endif
@if($screen === 'unit')
<div class="card"><div class="card-body py-3 d-flex flex-wrap gap-4">@foreach(['Required' => $items->sum('required'), 'Present' => $items->sum('present'), 'Missing' => $items->sum(fn($i) => max(0,$i->required-$i->present)), 'Damaged' => $items->sum('damaged')] as $label => $number)<div><span class="text-muted">{{ $label }}</span><h4 class="mb-0">{{ $number }}</h4></div>@endforeach</div></div>
<div class="card"><div class="card-header"><h5 class="mb-0">{{ $property->building?->building_name }} — {{ $property->name }}</h5></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Item / Room</th><th>Required</th><th>Present</th><th>Damaged</th><th>Missing</th><th>Replacement AED</th><th>Actions</th></tr></thead><tbody>
@forelse($items as $item)<tr><td><strong>{{ $item->name }}</strong><br><small class="text-muted">{{ $item->room }}</small></td><td>{{ $item->required }}</td><td>{{ $item->present }}</td><td>{{ $item->damaged }}</td><td><span class="badge {{ $item->required > $item->present ? 'bg-warning' : 'bg-success' }}">{{ max(0,$item->required-$item->present) }}</span></td><td>{{ number_format($item->replacement_cost,2) }}</td><td class="text-nowrap"><button class="btn btn-light btn-sm" data-bs-toggle="modal" data-bs-target="#edit-{{ $item->id }}">Edit</button> <button class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#move-{{ $item->id }}">Movement</button></td></tr>@empty<tr><td colspan="7" class="text-center py-4">No inventory yet. Add the required items, then request an initial count.</td></tr>@endforelse
</tbody></table></div><div class="card-footer text-muted small">Damaged items are included in Present. Missing = Required − Present (minimum zero). Replacement costs are estimates, not guest charges.</div></div>
@endif
@if($screen === 'history')
@include('admin.inspections.inventory-tasks')
<div class="card"><div class="card-header"><h5 class="mb-0">Movement history</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Date</th><th>Item</th><th>Type</th><th>Stock change</th><th>Damage change</th><th>Reason</th><th>By</th></tr></thead><tbody>@forelse($movements as $move)<tr><td>{{ $move->created_at }}</td><td>{{ $move->name }}</td><td>{{ str_replace('_',' ',$move->type) }}</td><td>{{ $move->quantity }}</td><td>{{ $move->damaged_change }}</td><td>{{ $move->reason }}</td><td>{{ $move->actor }}</td></tr>@empty<tr><td colspan="7">No movements recorded.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $movements->links() }}</div></div>
@endif
<div class="modal fade" id="addInventory" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('admin.inventory.store') }}">@csrf<input type="hidden" name="property_id" value="{{ $property->id }}"><div class="modal-header"><h5>Add required item</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body row g-3"><label class="col-6">Item<input name="name" class="form-control" maxlength="150" required></label><label class="col-6">Room<input name="room" class="form-control" maxlength="100" required></label><label class="col-6">Required quantity<input type="number" min="0" name="required" class="form-control" required></label><label class="col-6">Replacement cost (AED)<input type="number" min="0" step="0.01" name="replacement_cost" value="0" class="form-control" required></label><p class="text-muted small">Actual stock starts at zero until receipt or approved inspection.</p></div><div class="modal-footer"><button class="btn btn-primary">Add item</button></div></form></div></div>
<div class="modal fade" id="requestInspection" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('admin.inspection.request') }}">@csrf<input type="hidden" name="property_id" value="{{ $property->id }}"><div class="modal-header"><h5>Request unit inspection</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body row g-3"><label class="col-12">Assign employee<select class="form-select" name="assigned_to" required><option value="">Select operations / maintenance employee</option>@foreach($maintainers as $employee)<option value="{{ $employee->id }}">{{ $employee->name }}</option>@endforeach</select></label><label class="col-6">Type<select class="form-select" name="inspection_type"><option value="check_in">Check-in (booking required)</option><option value="check_out">Check-out (booking required)</option><option value="routine" selected>Routine / inventory count</option><option value="maintenance">Maintenance</option><option value="cleaning">Cleaning</option></select></label><label class="col-6">Due date<input type="date" name="due_date" class="form-control" value="{{ now()->toDateString() }}" required></label><label class="col-12">Related booking<select name="booking_id" class="form-select"><option value="">None — routine / maintenance</option>@foreach($bookings as $booking)<option value="{{ $booking->id }}">{{ $booking->booking_reference }} — {{ $booking->guest_name }}</option>@endforeach</select></label><label class="col-12">Office instructions<textarea class="form-control" name="description" required maxlength="3000"></textarea></label><p class="small text-muted">Appears under My Inspections in the assigned maintainer app. Routine inspections do not require a booking.</p></div><div class="modal-footer"><button class="btn btn-primary">Send inspection request</button></div></form></div></div>
@foreach($items as $item)
<div class="modal fade" id="edit-{{ $item->id }}" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('admin.inventory.update',$item) }}">@csrf @method('PUT')<div class="modal-header"><h5>{{ $item->name }} — Requirements</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body row g-3"><label class="col-6">Required<input type="number" min="0" name="required" value="{{ $item->required }}" class="form-control" required></label><label class="col-6">Replacement AED<input type="number" min="0" step="0.01" name="replacement_cost" value="{{ $item->replacement_cost }}" class="form-control" required></label></div><div class="modal-footer"><button class="btn btn-primary">Save requirements</button></div></form></div></div>
<div class="modal fade" id="move-{{ $item->id }}" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('admin.inventory.move',$item) }}">@csrf<div class="modal-header"><h5>{{ $item->name }} — Stock movement</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body row g-3"><label class="col-6">Action<select name="type" class="form-select"><option value="receive">Receive good stock</option><option value="transfer">Transfer good stock</option><option value="replace">Replace damaged stock</option><option value="repair">Repair damaged stock</option><option value="dispose">Dispose damaged stock</option></select></label><label class="col-6">Quantity<input type="number" min="1" name="quantity" class="form-control" required></label><label class="col-12">Destination (transfers only)<select name="target_property_id" class="form-select"><option value="">Select destination</option>@foreach($properties as $unit)@if($unit->id !== $property->id)<option value="{{ $unit->id }}">{{ $unit->building?->building_name }} — {{ $unit->name }}</option>@endif @endforeach</select></label><label class="col-12">Reason / reference<textarea name="reason" class="form-control" minlength="5" maxlength="1000" required></textarea></label></div><div class="modal-footer"><button class="btn btn-primary">Record movement</button></div></form></div></div>
@endforeach
@endif
@endsection
