@extends('layouts.app')
@section('title', 'Owner Charges & Invoices')
@section('content')
<div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">{{ $landlord->name }}</h4><p class="text-muted mb-0">Owner onboarding charges, collections, actual costs and profit</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createOwnerInvoice"><i class="ri-add-line me-1"></i>Create Tax Invoice</button></div>
    @include('admin.landlords.partials.profile-tabs', ['landlord'=>$landlord])

    @php
        $all=$summaryInvoices; $open=$all->sum(fn($i)=>$i->balance_due); $sales=$all->sum('subtotal'); $costs=$all->sum(fn($i)=>$i->actual_cost);
    @endphp
    <div class="row g-3 mb-3">
        @foreach([['Invoice Sales',$sales,'primary','ri-file-list-3-line'],['Outstanding',$open,'danger','ri-time-line'],['Actual Cost',$costs,'warning','ri-shopping-cart-line'],['Gross Profit',$sales-$costs,'success','ri-line-chart-line']] as [$label,$amount,$color,$icon])
        <div class="col-6 col-xl-3"><div class="card h-100"><div class="card-body d-flex align-items-center gap-3"><span class="avatar-md rounded-circle bg-{{ $color }}-subtle text-{{ $color }} d-inline-flex align-items-center justify-content-center"><i class="{{ $icon }} fs-24"></i></span><div><small class="text-muted">{{ $label }}</small><h5 class="mb-0">AED {{ number_format($amount,2) }}</h5></div></div></div></div>
        @endforeach
    </div>

    <div class="card"><div class="card-header"><h5 class="mb-0">Owner Invoice Register</h5></div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Invoice</th><th>Unit</th><th>Sale</th><th>Paid / Balance</th><th>Cost & Profit</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
    @forelse($invoices as $invoice)
        @php($costColor=['pending'=>'warning','provisional'=>'info','final'=>'success'][$invoice->cost_status])
        <tr><td><a href="{{ route('admin.landlord.owner-invoices.pdf',$invoice) }}" class="fw-semibold">{{ $invoice->invoice_number }}</a><br><small class="text-muted">{{ $invoice->invoice_date->format('d M Y') }}</small></td><td>{{ $invoice->property?->name }}<br><small class="text-muted">{{ $invoice->property?->building?->building_name }}</small></td><td><strong>AED {{ number_format((float)$invoice->total_amount,2) }}</strong><br><small class="text-muted">VAT {{ number_format((float)$invoice->vat_amount,2) }}</small></td><td><span class="text-success">AED {{ number_format($invoice->paid_amount,2) }}</span><br><span class="text-danger">Due AED {{ number_format($invoice->balance_due,2) }}</span></td><td><span class="badge bg-{{ $costColor }}-subtle text-{{ $costColor }}">Cost {{ ucfirst($invoice->cost_status) }}</span><br><small>Cost AED {{ number_format($invoice->actual_cost,2) }} · Profit AED {{ number_format($invoice->profit,2) }}</small></td><td><span class="badge {{ $invoice->status==='paid'?'bg-success':($invoice->status==='partially_paid'?'bg-info':'bg-danger') }}">{{ ucfirst(str_replace('_',' ',$invoice->status)) }}</span></td><td class="text-end"><div class="btn-group"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.landlord.owner-invoices.pdf',$invoice) }}"><i class="ri-file-pdf-line"></i></a><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#email{{ $invoice->id }}"><i class="ri-mail-send-line"></i></button>@if($invoice->balance_due>0)<button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#pay{{ $invoice->id }}">Payment</button>@endif<button class="btn btn-sm btn-outline-dark" data-bs-toggle="modal" data-bs-target="#detail{{ $invoice->id }}">Details</button></div></td></tr>
    @empty<tr><td colspan="7" class="text-center py-5 text-muted"><i class="ri-bill-line fs-32 d-block mb-2"></i>No owner invoices yet.</td></tr>@endforelse
    </tbody></table></div><div class="card-footer">{{ $invoices->links('pagination::bootstrap-5') }}</div></div>
</div>

<div class="modal fade" id="createOwnerInvoice" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><form class="modal-content" method="post" action="{{ route('admin.landlord.owner-invoices.store',$landlord) }}">@csrf
<div class="modal-header bg-primary text-white"><div><h5 class="modal-title text-white">New Owner Onboarding Tax Invoice</h5><small>Issue now; actual supplier cost can remain pending</small></div><button class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div>
<div class="modal-body"><div class="row g-3 mb-4"><div class="col-md-5"><label class="form-label">Unit</label><select name="property_id" class="form-select" required><option value="">Select unit</option>@foreach($properties as $property)<option value="{{ $property->id }}">{{ $property->name }} — {{ $property->building?->building_name ?? 'No Building' }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Invoice Date</label><input type="date" name="invoice_date" value="{{ today()->toDateString() }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Due Date</label><input type="date" name="due_date" value="{{ today()->addDays(7)->toDateString() }}" class="form-control"></div></div>
<div class="d-flex justify-content-between align-items-center mb-2"><h6 class="mb-0">Invoice Items</h6><button type="button" id="addOwnerLine" class="btn btn-sm btn-outline-primary"><i class="ri-add-line"></i>Add Item</button></div>
<div id="ownerInvoiceLines"></div><div class="alert alert-warning mt-3"><i class="ri-information-line me-1"></i><strong>Cost Pending:</strong> Issue the owner invoice using agreed selling prices. Link supplier bills later to calculate final profit.</div><label class="form-label">Notes</label><textarea name="notes" class="form-control" rows="2" placeholder="Contract, furnishing package or startup details"></textarea></div>
<div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Create & Post Invoice</button></div></form></div></div>

@foreach($invoices as $invoice)
@php($costColor=['pending'=>'warning','provisional'=>'info','final'=>'success'][$invoice->cost_status])
<div class="modal fade" id="pay{{ $invoice->id }}" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="{{ route('admin.landlord.owner-invoices.payment',$invoice) }}">@csrf<div class="modal-header"><div><h5 class="modal-title">Record Invoice Payment</h5><small class="text-muted">{{ $invoice->invoice_number }} · Due AED {{ number_format($invoice->balance_due,2) }}</small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Payment Date</label><input type="date" name="payment_date" value="{{ today()->toDateString() }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Amount</label><input type="number" name="amount" step="0.01" min="0.01" max="{{ $invoice->balance_due }}" value="{{ $invoice->balance_due }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Method</label><select name="method" class="form-select owner-payment-method" required><option value="bank_transfer">Bank Transfer</option><option value="cash">Cash</option><option value="cash_deposit">Cash Deposit</option><option value="rent_adjustment">Adjust from Owner Rental Income</option></select></div><div class="col-md-6 owner-payment-account"><label class="form-label">Received Into</label><select name="bank_account_id" class="form-select"><option value="">Select bank/cash account</option>@foreach($bankAccounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Reference</label><input name="reference" class="form-control"></div><div class="col-md-6"><label class="form-label">Notes</label><input name="notes" class="form-control"></div></div><div class="alert alert-info mt-3 mb-0 rent-note d-none">This records settlement against existing rental income. It does not create a false bank receipt or duplicate owner-statement credit.</div></div><div class="modal-footer"><button class="btn btn-primary">Save Payment</button></div></form></div></div>

<div class="modal fade" id="detail{{ $invoice->id }}" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><div><h5 class="modal-title">{{ $invoice->invoice_number }}</h5><small class="text-muted">Invoice, collections, cost and profit audit</small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">
<div class="row g-3"><div class="col-lg-7"><div class="card border"><div class="card-header fw-semibold">Sale Items</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Description</th><th>Qty</th><th>VAT</th><th class="text-end">Total</th></tr></thead><tbody>@foreach($invoice->lines as $line)<tr><td>{{ $line->description }}</td><td>{{ $line->quantity }}</td><td>{{ ucfirst($line->vat_mode) }} {{ $line->vat_rate }}%</td><td class="text-end">AED {{ number_format((float)$line->gross_amount,2) }}</td></tr>@endforeach</tbody></table></div></div>
<div class="card border"><div class="card-header fw-semibold">Payment History</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th class="text-end">Amount</th></tr></thead><tbody>@forelse($invoice->payments as $payment)<tr><td>{{ $payment->payment_date->format('d M Y') }}</td><td>{{ ucfirst(str_replace('_',' ',$payment->method)) }}</td><td>{{ $payment->reference ?: '-' }}</td><td class="text-end text-success">AED {{ number_format((float)$payment->amount,2) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted">Unpaid</td></tr>@endforelse</tbody></table></div></div></div>
<div class="col-lg-5"><div class="card border"><div class="card-header d-flex justify-content-between"><strong>Actual Supplier Cost</strong><span class="badge bg-{{ $costColor }}-subtle text-{{ $costColor }}">{{ ucfirst($invoice->cost_status) }}</span></div><div class="card-body"><div class="d-flex justify-content-between mb-2"><span>Sale excluding VAT</span><strong>AED {{ number_format((float)$invoice->subtotal,2) }}</strong></div><div class="d-flex justify-content-between mb-2"><span>Linked actual cost</span><strong>AED {{ number_format($invoice->actual_cost,2) }}</strong></div><div class="d-flex justify-content-between border-top pt-2 text-success"><span>Current gross profit</span><strong>AED {{ number_format($invoice->profit,2) }}</strong></div>
@if(!$invoice->cost_finalized)<form method="post" action="{{ route('admin.landlord.owner-invoices.cost',$invoice) }}" class="mt-3">@csrf<label class="form-label">Link approved supplier expenses</label><select name="expense_ids[]" multiple class="form-select" size="5">@foreach($availableExpenses->where('property_id',$invoice->property_id) as $expense)<option value="{{ $expense->id }}">{{ $expense->expense_no }} · {{ $expense->description }} · AED {{ number_format((float)$expense->net_amount,2) }}</option>@endforeach</select><button class="btn btn-outline-primary w-100 mt-2">Link Selected Costs</button></form><form method="post" action="{{ route('admin.landlord.owner-invoices.cost.finalize',$invoice) }}" class="mt-2">@csrf<button class="btn btn-success w-100" onclick="return confirm('Finalize actual cost for this invoice?')">Mark Cost Final</button></form>@endif
</div></div></div></div></div><div class="modal-footer"><a class="btn btn-primary" href="{{ route('admin.landlord.owner-invoices.pdf',$invoice) }}"><i class="ri-file-pdf-line me-1"></i>Download Tax Invoice</a></div></div></div></div>
<div class="modal fade" id="email{{ $invoice->id }}" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="{{ route('admin.landlord.owner-invoices.email',$invoice) }}">@csrf<div class="modal-header"><div><h5 class="modal-title">Email Owner Tax Invoice</h5><small class="text-muted">Branded HTML email with official PDF attachment</small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label">Recipient</label><input type="email" name="recipient" value="{{ $landlord->email }}" class="form-control" required></div><div class="col-12"><label class="form-label">Subject</label><input name="subject" class="form-control" value="Owner Tax Invoice {{ $invoice->invoice_number }} — {{ \App\Support\AppSettings::get('invoice_legal_name','PATTERN Vacation Homes Rental') }}"></div><div class="col-12"><label class="form-label">Message (optional)</label><textarea name="message" rows="4" class="form-control"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-primary"><i class="ri-send-plane-fill me-1"></i>Send Email & PDF</button></div></form></div></div>
@endforeach
@endsection
@push('scripts')<script>
let ownerLineIndex=0; const vatRate={{ (float)\App\Support\AppSettings::get('default_vat_rate',5) }};
function addOwnerLine(description='', price=''){const i=ownerLineIndex++;document.querySelector('#ownerInvoiceLines').insertAdjacentHTML('beforeend',`<div class="border rounded-3 p-3 mb-2 owner-line"><div class="row g-2 align-items-end"><div class="col-md-5"><label class="form-label">Item / Service</label><input name="lines[${i}][description]" value="${description}" class="form-control" placeholder="Furniture package, startup fee, DTCM permit..." required></div><div class="col-md-2"><label class="form-label">Quantity</label><input type="number" step="0.01" min="0.01" name="lines[${i}][quantity]" value="1" class="form-control" required></div><div class="col-md-2"><label class="form-label">Unit Sale Price</label><input type="number" step="0.01" min="0" name="lines[${i}][unit_price]" value="${price}" class="form-control" required></div><div class="col-md-2"><label class="form-label">VAT</label><select name="lines[${i}][vat_mode]" class="form-select"><option value="excluded">${vatRate}% Excluded</option><option value="included">${vatRate}% Included</option><option value="none">No VAT</option></select></div><div class="col-md-1"><button type="button" class="btn btn-soft-danger w-100" onclick="this.closest('.owner-line').remove()"><i class="ri-delete-bin-line"></i></button></div></div></div>`)}
document.querySelector('#addOwnerLine')?.addEventListener('click',()=>addOwnerLine()); addOwnerLine('Furniture / Fit-out Package'); addOwnerLine('Startup & DTCM Setup Fee');
document.querySelectorAll('.owner-payment-method').forEach(select=>select.addEventListener('change',()=>{const form=select.closest('form'),rent=select.value==='rent_adjustment';form.querySelector('.owner-payment-account').classList.toggle('d-none',rent);form.querySelector('.rent-note').classList.toggle('d-none',!rent);form.querySelector('[name="bank_account_id"]').required=!rent;}));
</script>@endpush
