@php
    $logo=public_path('assets/images/pattern-bilingual-logo.png');
    $company=\App\Support\AppSettings::get('invoice_legal_name',\App\Support\AppSettings::get('invoice_establishment_name','PATTERN Vacation Homes Rental'));
    $address=\App\Support\AppSettings::get('invoice_address','Dubai, U.A.E.');
    $trn=\App\Support\AppSettings::get('invoice_trn','101001557300003');
    $phone=\App\Support\AppSettings::get('company_phone','0527687168');
    $email=\App\Support\AppSettings::get('company_email','customerservice@pattern.ae');
@endphp
<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:11mm 12mm 15mm;footer:html_footer}body{font-family:DejaVu Sans,Arial,sans-serif;color:#20242b;font-size:8.5px}.header{width:100%;border-collapse:collapse}.header td{vertical-align:top}.logo{width:175px}.company{text-align:right;line-height:1.45}.company strong{font-size:10px}.rule{border-top:2px solid #222;margin:10px 0}.title{font-size:18px;font-weight:bold;border-left:4px solid #111;padding-left:8px;margin:12px 0}.meta{width:100%;border-collapse:collapse;margin-bottom:10px}.meta td{padding:3px 5px}.meta .box{border:1px solid #999;background:#fafafa}.section{font-size:11px;font-weight:bold;margin:13px 0 5px}.table{width:100%;border-collapse:collapse}.table th{background:#3e4247;color:#fff;text-align:left;padding:5px;border:1px solid #3e4247}.table td{border:1px solid #aeb3b8;padding:5px;vertical-align:top}.right{text-align:right!important;white-space:nowrap}.center{text-align:center}.muted{color:#6c737e}.summary{margin-top:11px}.summary td{border:0;border-bottom:1px solid #d2d5d8;padding:6px}.summary .group td{background:#f4f5f6;font-weight:bold}.summary .movement td{font-weight:bold;border-top:2px solid #555}.summary .net td{font-weight:bold;color:#fff;background:#30353a;border:0;font-size:12px;padding:9px 6px}.formula-note{font-size:7.5px;color:#69717a;margin:5px 0 0}.green{color:#157a4d}.red{color:#c53c45}.detail-title{margin-top:18px;padding:6px 8px;background:#eceeef;border-left:3px solid #333;font-weight:bold}.details th{font-size:7.5px}.details td{font-size:7.8px}.description strong,.description span{display:block}.description span{color:#68717e;margin-top:2px}.footer{text-align:center;border-top:1px solid #bbb;color:#747b85;padding-top:4px;font-size:7px}.empty{text-align:center;color:#777;padding:16px}.page-break{page-break-before:always}
</style></head><body>
<htmlpagefooter name="footer"><div class="footer">Generated by PATTERN Holiday Homes Management System | {{ $landlord->name }} | {{ now()->format('d M Y H:i') }} | Page {PAGENO} of {nbpg}</div></htmlpagefooter>
<table class="header"><tr><td width="48%">@if(file_exists($logo))<img class="logo" src="{{ $logo }}" alt="PATTERN">@endif</td><td width="52%" class="company"><strong>{{ strtoupper($company) }}</strong><br>{{ $address }}<br>TRN {{ $trn }}<br>{{ $phone }}<br>{{ $email }}</td></tr></table>
<div class="title">Owner Statement</div>
<table class="meta"><tr><td width="18%">Owner</td><td class="box">{{ $landlord->name }}</td></tr><tr><td>Statement Period</td><td class="box">{{ $period['from']->format('d M Y') }} - {{ $period['to']->format('d M Y') }}</td></tr></table>

<div class="section">Reservation Summary</div>
<table class="table"><thead><tr><th>Reservation Code</th><th>Unit / Building</th><th>Invoice Period</th><th class="right">Rent Received</th><th class="right">Management Fee</th><th class="right">Owner Net</th></tr></thead><tbody>
@forelse($reservations as $invoice)<tr><td>{{ $invoice->booking?->booking_reference }}<br><span class="muted">{{ $invoice->type_label }}</span></td><td>{{ $invoice->booking?->property?->name ?? '-' }}<br><span class="muted">{{ $invoice->booking?->property?->building?->building_name ?? '' }}</span></td><td>{{ $invoice->period_from?->format('d M Y') }}<br><span class="muted">to {{ $invoice->period_to?->format('d M Y') }}</span></td><td class="right green">{{ number_format((float)$invoice->statement_rent_received,2) }}</td><td class="right red">- {{ number_format((float)$invoice->statement_management_fee,2) }}</td><td class="right"><strong>{{ number_format((float)$invoice->statement_net_rent,2) }}</strong></td></tr>@empty<tr><td colspan="6" class="empty">No booking periods in this statement period.</td></tr>@endforelse
</tbody></table>

<table class="table summary"><tbody>
<tr class="group"><td>Opening balance brought forward</td><td class="right">AED {{ number_format($openingBalance,2) }}</td></tr>
<tr><td>Rental income received</td><td class="right green">+ AED {{ number_format($summary['rent'],2) }}</td></tr>
@if($summary['other_credits'] > 0)<tr><td>Other credits</td><td class="right green">+ AED {{ number_format($summary['other_credits'],2) }}</td></tr>@endif
<tr><td>Management fee</td><td class="right red">- AED {{ number_format($summary['management'],2) }}</td></tr>
<tr><td>Owner expenses<br><span class="muted">@forelse($summary['expense_breakdown'] as $item){{ $item['label'] }}: AED {{ number_format($item['amount'],2) }}{{ !$loop->last ? ' | ' : '' }}@empty No owner expenses in this period @endforelse</span></td><td class="right red">- AED {{ number_format($summary['owner_expenses'],2) }}</td></tr>
@if($summary['other_debits'] > 0)<tr><td>Other deductions</td><td class="right red">- AED {{ number_format($summary['other_debits'],2) }}</td></tr>@endif
<tr><td>Payments made to owner</td><td class="right red">- AED {{ number_format($summary['payouts'],2) }}</td></tr>
<tr class="movement"><td>Net movement this period</td><td class="right {{ $summary['period_movement'] >= 0 ? 'green' : 'red' }}">{{ $summary['period_movement'] >= 0 ? '+' : '-' }} AED {{ number_format(abs($summary['period_movement']),2) }}</td></tr>
<tr class="net"><td>{{ $accountTotals['balance'] >= 0 ? 'Closing balance payable to owner' : 'Closing balance due from owner' }}</td><td class="right">AED {{ number_format(abs($accountTotals['balance']),2) }}</td></tr>
</tbody></table>
<div class="formula-note">Calculation: opening balance + all credits - all deductions and owner payments = closing balance.</div>

<div class="detail-title">Statement Details</div>
<table class="table details"><thead><tr><th style="width:12%">Date</th><th>Description</th><th style="width:14%" class="right">Credit</th><th style="width:14%" class="right">Debit</th><th style="width:15%" class="right">Balance</th></tr></thead><tbody>
@forelse($entries as $entry)<tr><td>{{ $entry->statement_date->format('d M Y') }}@if(!$entry->statement_date->isSameDay($entry->entry_date))<br><span class="muted">Paid {{ $entry->entry_date?->format('d M Y') }}</span>@endif</td><td class="description"><strong>{{ $entry->type_label }}@if($entry->property) - {{ $entry->property->name }}@if($entry->property->building) - {{ $entry->property->building->building_name }}@endif @endif</strong><br><span>{{ $entry->description ?: 'No additional description' }}</span></td><td class="right green">{{ $entry->direction==='credit' ? number_format((float)$entry->amount,2) : '-' }}</td><td class="right red">{{ $entry->direction==='debit' ? number_format((float)$entry->amount,2) : '-' }}</td><td class="right">{{ number_format((float)$entry->statement_balance,2) }}</td></tr>@empty<tr><td colspan="5" class="empty">No account entries in this period.</td></tr>@endforelse
</tbody></table>
</body></html>
