<?php

namespace Tests\Feature;

use App\Models\Building;
use App\Models\Property;
use App\Models\UnitDocument;
use App\Models\User;
use App\Notifications\DtcmPermitExpiring;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\UploadedFile;
use Tests\TestCase;

class DtcmPermitMonitoringTest extends TestCase
{
    use RefreshDatabase;

    public function test_admin_can_filter_urgent_dtcm_permits(): void
    {
        $admin = User::factory()->create(['role' => 'admin']);
        $owner = User::factory()->create(['role' => 'landlord']);
        $building = Building::create(['building_name' => 'Marina Tower', 'address' => 'Dubai']);
        $urgent = Property::create(['landlord_id' => $owner->id, 'building_id' => $building->id, 'name' => 'Unit 101', 'status' => 'vacant']);
        $valid = Property::create(['landlord_id' => $owner->id, 'building_id' => $building->id, 'name' => 'Unit 202', 'status' => 'vacant']);
        $urgent->unitDocuments()->create(['type' => 'dtcm_permit', 'reference_no' => 'DTCM-URGENT', 'expires_at' => today()->addDays(7), 'file_path' => 'urgent.pdf']);
        $valid->unitDocuments()->create(['type' => 'dtcm_permit', 'reference_no' => 'DTCM-VALID', 'expires_at' => today()->addDays(60), 'file_path' => 'valid.pdf']);

        $this->actingAs($admin)->get(route('admin.property.dtcm-permits', ['status' => 'urgent']))
            ->assertOk()->assertSee('DTCM-URGENT')->assertDontSee('DTCM-VALID');
    }

    public function test_dtcm_permit_added_through_wallet_appears_in_all_permits_list(): void
    {
        Storage::fake('public');
        $admin = User::factory()->create(['role' => 'admin']);
        $owner = User::factory()->create(['role' => 'landlord']);
        $property = Property::create(['landlord_id' => $owner->id, 'name' => 'Unit 707', 'status' => 'vacant']);

        $this->actingAs($admin)->post(route('admin.property.document-wallet.store', $property), [
            'type' => 'dtcm_permit', 'reference_no' => 'DTCM-WALLET-707',
            'issue_date' => today()->toDateString(),
            'document' => UploadedFile::fake()->create('dtcm.pdf', 50, 'application/pdf'),
        ])->assertRedirect(route('admin.property.dtcm-permits'))->assertSessionHasNoErrors();

        $this->actingAs($admin)->get(route('admin.property.dtcm-permits'))
            ->assertOk()->assertSee('DTCM-WALLET-707')->assertSee('Unit 707');
    }

    public function test_seven_day_reminder_is_sent_once_per_expiry_date(): void
    {
        Notification::fake();
        $admin = User::factory()->create(['role' => 'admin', 'is_active' => true]);
        $owner = User::factory()->create(['role' => 'landlord']);
        $property = Property::create(['landlord_id' => $owner->id, 'name' => 'Unit 303', 'status' => 'vacant']);
        $permit = $property->unitDocuments()->create(['type' => 'dtcm_permit', 'expires_at' => today()->addDays(7), 'file_path' => 'permit.pdf']);

        Artisan::call('dtcm:send-expiry-reminders');
        Artisan::call('dtcm:send-expiry-reminders');

        Notification::assertSentToTimes($admin, DtcmPermitExpiring::class, 1);
        $this->assertTrue($permit->fresh()->expiry_reminder_sent_for->equalTo($permit->expires_at));
    }

    public function test_owner_cannot_open_admin_dtcm_list(): void
    {
        $owner = User::factory()->create(['role' => 'landlord']);
        $this->actingAs($owner)->get(route('admin.property.dtcm-permits'))->assertForbidden();
    }

    public function test_admin_can_download_filtered_dtcm_excel_report_generated_by_system(): void
    {
        $admin = User::factory()->create(['role' => 'admin']);
        $owner = User::factory()->create(['role' => 'landlord']);
        $urgent = Property::create(['landlord_id' => $owner->id, 'name' => 'Export Unit 101', 'status' => 'vacant']);
        $valid = Property::create(['landlord_id' => $owner->id, 'name' => 'Hidden Unit 202', 'status' => 'vacant']);
        $urgent->unitDocuments()->create(['type' => 'dtcm_permit', 'reference_no' => 'DTCM-EXPORT-101', 'expires_at' => today()->addDays(5), 'file_path' => 'urgent.pdf']);
        $valid->unitDocuments()->create(['type' => 'dtcm_permit', 'reference_no' => 'DTCM-HIDDEN-202', 'expires_at' => today()->addDays(60), 'file_path' => 'valid.pdf']);

        $response = $this->actingAs($admin)->get(route('admin.property.dtcm-permits.excel', ['status' => 'urgent']));
        $response->assertOk()->assertDownload('dtcm-permit-report-' . now()->format('Y-m-d') . '.csv');
        $report = $response->streamedContent();
        $this->assertStringContainsString('"Generated by",System', $report);
        $this->assertStringContainsString('DTCM-EXPORT-101', $report);
        $this->assertStringNotContainsString('DTCM-HIDDEN-202', $report);
    }

    public function test_admin_can_download_dtcm_pdf_report(): void
    {
        $admin = User::factory()->create(['role' => 'admin']);

        $this->actingAs($admin)->get(route('admin.property.dtcm-permits.pdf'))
            ->assertOk()->assertDownload('dtcm-permit-report-' . now()->format('Y-m-d') . '.pdf');
    }
}
