<!doctype html><html><head><meta charset="utf-8"><title>Accounting Report</title><style>
@page{margin:22px}body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:9px}h1{font-size:18px;margin:0;color:#102a56}h2{font-size:13px;color:#102a56;border-bottom:2px solid #102a56;padding-bottom:4px;margin:18px 0 7px}.meta{color:#667085;margin:4px 0 14px}.summary{width:100%;border-collapse:separate;border-spacing:6px}.summary td{background:#eef3f8;padding:9px}.summary strong{display:block;font-size:13px;margin-top:3px}table.report{width:100%;border-collapse:collapse;margin-bottom:12px}.report th,.report td{border:1px solid #d7dde7;padding:5px;vertical-align:top}.report th{background:#102a56;color:#fff;text-align:left}.right{text-align:right}.total td{font-weight:bold;background:#edf2f7}.positive{color:#14804a}.negative{color:#c43131}.page-break{page-break-before:always}
</style></head><body>
<h1>{{ $report === 'combined' ? 'Combined Accounting Reports' : ['financial'=>'Profit & Loss / Financial Report','receivables'=>'Receivables Report','agency'=>'Agent Commission Report','expenses'=>'Expense Report','utilities'=>'Utilities Report'][$report] }}</h1>
<p class="meta">Period: {{ $from->format('d M Y') }} — {{ $to->format('d M Y') }} · Generated {{ now()->format('d M Y H:i') }}</p>

@if(in_array($report,['financial','combined']))
<h2>Profit &amp; Loss</h2><table class="summary"><tr><td>Posted income<strong>AED {{ number_format($profitLossTotals['income'],2) }}</strong></td><td>Posted expenses<strong>AED {{ number_format($profitLossTotals['expense'],2) }}</strong></td><td>Net profit / (loss)<strong class="{{ $profitLossTotals['net_profit'] < 0 ? 'negative':'positive' }}">AED {{ number_format($profitLossTotals['net_profit'],2) }}</strong></td></tr></table>
<table class="report"><thead><tr><th>Account</th><th class="right">Income</th><th class="right">Expense</th></tr></thead><tbody>
@foreach($incomeAccounts as $row)<tr><td>{{ $row['code'] }} · {{ $row['name'] }}</td><td class="right">AED {{ number_format($row['amount'],2) }}</td><td></td></tr>@endforeach
@foreach($expenseAccounts as $row)<tr><td>{{ $row['code'] }} · {{ $row['name'] }}</td><td></td><td class="right">AED {{ number_format($row['amount'],2) }}</td></tr>@endforeach
<tr class="total"><td>Totals</td><td class="right">AED {{ number_format($profitLossTotals['income'],2) }}</td><td class="right">AED {{ number_format($profitLossTotals['expense'],2) }}</td></tr></tbody></table>
<h2>Cash Flow</h2><table class="summary"><tr><td>Opening<strong>AED {{ number_format($cashFlowSummary['opening'],2) }}</strong></td><td>Inflows<strong>AED {{ number_format($cashFlowSummary['inflow'],2) }}</strong></td><td>Outflows<strong>AED {{ number_format($cashFlowSummary['outflow'],2) }}</strong></td><td>Closing<strong>AED {{ number_format($cashFlowSummary['closing'],2) }}</strong></td></tr></table>
@endif

@if(in_array($report,['receivables','combined']))
<h2 class="{{ $report==='combined'?'page-break':'' }}">Receivables</h2><table class="summary"><tr>@foreach(['0–30 days'=>'current','31–60 days'=>'31_60','61–90 days'=>'61_90','Over 90 days'=>'over_90'] as $label=>$key)<td>{{ $label }}<strong>AED {{ number_format($receivableAgeing[$key] ?? 0,2) }}</strong></td>@endforeach</tr></table>
<table class="report"><thead><tr><th>Invoice</th><th>Customer / Booking</th><th>Issue date</th><th class="right">Outstanding</th></tr></thead><tbody>@forelse($receivableRows as $invoice)<tr><td>{{ $invoice->invoice_number }}</td><td>{{ $invoice->booking?->guest_name ?? '-' }} · {{ $invoice->booking?->booking_reference ?? '-' }}</td><td>{{ $invoice->issue_date?->format('d M Y') }}</td><td class="right">AED {{ number_format($invoice->balance_due,2) }}</td></tr>@empty<tr><td colspan="4">No outstanding booking receivables.</td></tr>@endforelse</tbody></table>
@endif

@if(in_array($report,['agency','combined']))
<h2 class="{{ $report==='combined'?'page-break':'' }}">Agent Commission Report</h2><table class="summary"><tr><td>Agency fee collected<strong>AED {{ number_format($agencyFeeTotals['collected'],2) }}</strong></td><td>Agent commission payable<strong>AED {{ number_format($agencyFeeTotals['agent_commission'],2) }}</strong></td><td>Company share<strong>AED {{ number_format($agencyFeeTotals['company_share'],2) }}</strong></td></tr></table>
<table class="report"><thead><tr><th>Agent</th><th class="right">Bookings</th><th class="right">Fee collected</th><th class="right">Commission</th><th class="right">Company share</th></tr></thead><tbody>@forelse($agencyFeeByAgent as $row)<tr><td>{{ $row['agent']->name }}</td><td class="right">{{ $row['bookings'] }}</td><td class="right">AED {{ number_format($row['agency_fee'],2) }}</td><td class="right">AED {{ number_format($row['commission'],2) }}</td><td class="right">AED {{ number_format($row['company_share'],2) }}</td></tr>@empty<tr><td colspan="5">No agent commission in this period.</td></tr>@endforelse<tr class="total"><td colspan="2">Totals</td><td class="right">AED {{ number_format($agencyFeeTotals['collected'],2) }}</td><td class="right">AED {{ number_format($agencyFeeTotals['agent_commission'],2) }}</td><td class="right">AED {{ number_format($agencyFeeTotals['company_share'],2) }}</td></tr></tbody></table>
<table class="report"><thead><tr><th>Date / Invoice</th><th>Booking</th><th>Agent</th><th class="right">Agency fee</th><th class="right">Commission</th><th class="right">Company</th></tr></thead><tbody>@foreach($agencyFeeRows as $row)<tr><td>{{ $row['payment']->payment_date?->format('d M Y') }}<br>{{ $row['invoice']?->invoice_number }}</td><td>{{ $row['booking']?->booking_reference ?? '-' }}</td><td>{{ $row['agent']?->name ?? 'Direct / no agent' }} ({{ number_format($row['commission_rate'],2) }}%)</td><td class="right">AED {{ number_format($row['agency_fee'],2) }}</td><td class="right">AED {{ number_format($row['agent_commission'],2) }}</td><td class="right">AED {{ number_format($row['company_share'],2) }}</td></tr>@endforeach</tbody></table>
@endif

@if(in_array($report,['expenses','combined']))
<h2 class="{{ $report==='combined'?'page-break':'' }}">Expenses</h2><table class="summary"><tr><td>Entries<strong>{{ $expenseTotals['count'] }}</strong></td><td>Net<strong>AED {{ number_format($expenseTotals['net'],2) }}</strong></td><td>VAT<strong>AED {{ number_format($expenseTotals['vat'],2) }}</strong></td><td>Gross<strong>AED {{ number_format($expenseTotals['gross'],2) }}</strong></td></tr></table>
<table class="report"><thead><tr><th>Date</th><th>Expense</th><th>Category</th><th>Unit</th><th class="right">Gross</th></tr></thead><tbody>@forelse($expenseRows as $expense)<tr><td>{{ $expense->expense_date?->format('d M Y') }}</td><td>{{ $expense->expense_no }} · {{ $expense->description }}</td><td>{{ $expenseCategories[$expense->category] ?? str($expense->category)->headline() }}</td><td>{{ $expense->property?->name ?? 'General' }}</td><td class="right">AED {{ number_format($expense->gross_amount,2) }}</td></tr>@empty<tr><td colspan="5">No expenses in this period.</td></tr>@endforelse</tbody></table>
@endif

@if(in_array($report,['utilities','combined']))
<h2 class="{{ $report==='combined'?'page-break':'' }}">Utilities</h2><table class="report"><thead><tr><th>Utility type</th><th class="right">Period total</th></tr></thead><tbody>@forelse($utilityByType as $type=>$total)<tr><td>{{ str($type)->replace('_',' ')->headline() }}</td><td class="right">AED {{ number_format($total,2) }}</td></tr>@empty<tr><td colspan="2">No utility bills in this period.</td></tr>@endforelse</tbody></table>
<h2>Outstanding Utility Bills</h2><table class="report"><thead><tr><th>Account</th><th>Unit</th><th>Due date</th><th>Status</th><th class="right">Amount</th></tr></thead><tbody>@forelse($outstandingBills as $bill)<tr><td>{{ $bill->account?->account_name ?? '-' }}</td><td>{{ $bill->property?->name ?? '-' }}</td><td>{{ $bill->due_date?->format('d M Y') }}</td><td>{{ str($bill->status)->headline() }}</td><td class="right">AED {{ number_format($bill->total_amount,2) }}</td></tr>@empty<tr><td colspan="5">No outstanding utility bills.</td></tr>@endforelse</tbody></table>
@endif
</body></html>
