@extends('layouts.app')
@section('content')
@include('admin.accounting.partials.module-nav')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">{{ $selectedAccount?->name ?? 'All Account Statements' }}</h4><p class="text-muted mb-0">Complete posted debit and credit movements with running balances.</p></div><a href="{{ route('admin.accounting.bank-accounts') }}" class="btn btn-light">Bank & Cash</a></div>
<div class="card"><div class="card-body border-bottom"><form method="get" action="{{ $selectedAccount ? route('admin.accounting.bank-account.statement',$selectedAccount) : route('admin.accounting.bank-statements') }}" class="row g-2 align-items-end">@if(!$selectedAccount)<div class="col-md-3"><label class="form-label">Account</label><select name="account_id" class="form-select"><option value="">All accounts</option>@foreach($bankAccounts as $item)<option value="{{ $item->id }}" @selected(request('account_id')==$item->id)>{{ $item->name }}</option>@endforeach</select></div>@endif<div class="col-md-3"><label class="form-label">From</label><input type="date" name="date_from" value="{{ request('date_from') }}" class="form-control"></div><div class="col-md-3"><label class="form-label">To</label><input type="date" name="date_to" value="{{ request('date_to') }}" class="form-control"></div><div class="col-md-3 d-flex gap-2"><button class="btn btn-primary flex-fill">Apply</button><a href="{{ $selectedAccount ? route('admin.accounting.bank-account.statement',$selectedAccount) : route('admin.accounting.bank-statements') }}" class="btn btn-light">Reset</a></div></form></div>
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="bg-light-subtle"><tr><th>Date</th><th>Entry / Transfer</th><th>Account</th><th>Description</th><th>Reference</th><th class="text-end">Debit</th><th class="text-end">Credit</th><th class="text-end">Running Balance</th></tr></thead><tbody>
@if($selectedAccount)<tr class="table-light"><td colspan="7" class="fw-semibold">Opening Balance</td><td class="text-end fw-bold">{{ $selectedAccount->currency }} {{ number_format((float)$selectedAccount->opening_balance,2) }}</td></tr>@endif
@forelse($entries as $entry)<tr><td>{{ $entry->entry_date?->format('d M Y') }}</td><td><strong>{{ $entry->entry_no }}</strong>@if($entry->bankTransfer)<div class="small text-primary">{{ $entry->bankTransfer->transfer_no }}</div>@endif</td><td>{{ $entry->paidFromAccount?->name }}</td><td>{{ $entry->description }}</td><td>{{ $entry->bankTransfer?->reference ?? $entry->transaction_reference ?? '—' }}</td><td class="text-end text-danger">{{ (float)$entry->debit>0?number_format((float)$entry->debit,2):'—' }}</td><td class="text-end text-success">{{ (float)$entry->credit>0?number_format((float)$entry->credit,2):'—' }}</td><td class="text-end fw-semibold">{{ $entry->paidFromAccount?->currency }} {{ number_format((float)($runningBalances[$entry->id]??0),2) }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-5">No account movements found.</td></tr>@endforelse
</tbody><tfoot><tr class="table-light"><th colspan="5">Totals</th><th class="text-end">{{ number_format((float)$entries->sum('debit'),2) }}</th><th class="text-end">{{ number_format((float)$entries->sum('credit'),2) }}</th><th></th></tr></tfoot></table></div></div>
@endsection
