@extends('layouts.app')
@section('title','User Activity Logs')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">User Activity Logs</h4><p class="text-muted mb-0">Login security and administrative activity with IP and device information.</p></div><span class="badge bg-primary-subtle text-primary">Read-only audit trail</span></div>
<div class="alert alert-warning py-2"><i class="ri-information-line me-1"></i>IP addresses identify the internet connection, not an exact physical address. Proxy/CDN forwarding values are retained separately for investigation.</div>
<div class="card"><div class="card-body border-bottom"><form class="row g-2 align-items-end">
<div class="col-md-3"><label class="form-label">User</label><select class="form-select" name="user_id"><option value="">All users</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(($filters['user_id']??'')==(string)$user->id)>{{ $user->name }} · {{ $user->email }}</option>@endforeach</select></div>
<div class="col-md-2"><label class="form-label">Activity</label><select class="form-select" name="event"><option value="">All activities</option>@foreach(['login_success'=>'Successful login','login_failed'=>'Failed login','logout'=>'Logout','admin_action'=>'Admin action'] as $key=>$label)<option value="{{ $key }}" @selected(($filters['event']??'')===$key)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-2"><label class="form-label">IP address</label><input class="form-control" name="ip" value="{{ $filters['ip']??'' }}" placeholder="Search IP"></div>
<div class="col-md-2"><label class="form-label">From</label><input type="date" class="form-control" name="date_from" value="{{ $filters['date_from']??'' }}"></div>
<div class="col-md-2"><label class="form-label">To</label><input type="date" class="form-control" name="date_to" value="{{ $filters['date_to']??'' }}"></div>
<div class="col-md-1"><button class="btn btn-primary w-100">Apply</button></div>
</form></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Dubai time</th><th>User</th><th>Activity</th><th>IP / Forwarded IP</th><th>Device</th><th>Route / Result</th></tr></thead><tbody>
@forelse($logs as $log)<tr><td class="text-nowrap">{{ $log->occurred_at?->timezone('Asia/Dubai')->format('d M Y H:i:s') }}</td><td><strong>{{ $log->user?->name ?? 'Unknown / failed login' }}</strong><small class="d-block text-muted">{{ $log->user_email }}</small></td><td><span class="badge {{ $log->event==='login_failed'?'bg-danger':($log->event==='login_success'?'bg-success':($log->event==='logout'?'bg-secondary':'bg-primary')) }}">{{ str($log->event)->replace('_',' ')->headline() }}</span><small class="d-block mt-1">{{ $log->description }}</small></td><td><code>{{ $log->ip_address ?: 'Unknown' }}</code>@if($log->forwarded_for && $log->forwarded_for!==$log->ip_address)<small class="d-block text-muted">Forwarded: {{ $log->forwarded_for }}</small>@endif</td><td>{{ $log->device }}<details><summary class="small text-primary">User agent</summary><small class="text-break">{{ $log->user_agent }}</small></details></td><td><code>{{ $log->method }} {{ $log->route_name }}</code><small class="d-block text-muted text-break">{{ $log->url_path }}</small>@if($log->status_code)<span class="badge {{ $log->status_code<400?'bg-success-subtle text-success':'bg-danger-subtle text-danger' }}">HTTP {{ $log->status_code }}</span> <small>{{ $log->duration_ms }} ms</small>@endif</td></tr>
@empty<tr><td colspan="6" class="text-center text-muted py-5">No activity logs match these filters. New activity is recorded after this update.</td></tr>@endforelse
</tbody></table></div>@if($logs->hasPages())<div class="card-footer">{{ $logs->links() }}</div>@endif</div>
@endsection
