<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign Cancellation</title><link href="{{ asset('assets/css/vendor.min.css') }}" rel="stylesheet"><link href="{{ asset('assets/css/app.min.css') }}" rel="stylesheet"><style>
body{background:#edf2f7}.wrap{max-width:1320px;margin:18px auto;padding:0 14px}.shell{border:0;border-radius:18px;box-shadow:0 18px 50px rgba(20,32,55,.12);overflow:hidden}.preview{height:calc(100vh - 135px);min-height:650px;overflow:auto;background:white;padding:24px;color:#172033;font-size:13px;line-height:1.65}.preview .head{text-align:center;border-bottom:3px solid #173b6c;padding-bottom:12px;margin-bottom:18px}.preview .head img{width:190px}.preview .head h1{font-size:22px;margin:8px 0 0;color:#173b6c}.preview .head h2{font-size:15px;margin:0;color:#b3873f}.preview .meta,.preview .sig{width:100%;border-collapse:collapse}.preview .meta{margin-bottom:18px}.preview .meta th,.preview .meta td,.preview .sig td{border:1px solid #d9e0ea;padding:9px;text-align:left}.preview .meta th{width:29%;background:#f2f5f9}.preview .section{font-size:15px;font-weight:bold;color:#173b6c;border-bottom:1px solid #b3873f;margin:18px 0 8px}.preview .sig{margin-top:24px}.preview .sig td{width:48%;vertical-align:top}.preview .sig .gap{width:4%;border:0}.preview .line{height:62px;border-bottom:1px solid #6b7280}.preview .sig-img{height:58px;max-width:190px}.preview .muted,.preview .foot{color:#657187;font-size:11px}.preview .foot{margin-top:20px;border-top:1px solid #d9e0ea;padding-top:7px;text-align:center}.sign-panel{position:sticky;top:16px}.signature-canvas{display:block;width:100%;height:420px;border:3px dashed #60748f;border-radius:16px;background:#fff;touch-action:none;cursor:crosshair}.sign-head{background:linear-gradient(135deg,#173b6c,#6350d9);color:white;padding:22px}.sign-head h3{color:white}.notice{background:#eef5ff;border:1px solid #c9dcfa;border-radius:11px;padding:12px;color:#244b78}@media(max-width:991px){.preview{height:auto;max-height:55vh;min-height:420px}.sign-panel{position:static}.signature-canvas{height:360px}}
</style></head><body><main class="wrap">
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row g-3"><div class="col-lg-7"><div class="card shell"><div class="card-header"><strong>{{ $cancellation->reference_no }}</strong> · Management Agreement Cancellation</div><div class="preview">@include('unit-cancellations.partials.document-content')</div></div></div>
<div class="col-lg-5"><div class="card shell sign-panel"><div class="sign-head"><h3 class="mb-1">{{ $party === 'owner' ? 'Owner Signature' : 'Company Countersignature' }}</h3><div>{{ $cancellation->status_label }}</div></div><div class="card-body p-4">
@php
    $alreadySigned = $party === 'owner' ? $cancellation->owner_signed_at : $cancellation->company_signed_at;
@endphp
@if($cancellation->status === 'expired')<div class="alert alert-danger">This signing link expired on {{ $cancellation->expires_at->format('d M Y') }}.</div>
@elseif($party === 'company' && !$cancellation->owner_signed_at)<div class="alert alert-warning">Waiting for the owner to sign first.</div>
@elseif($alreadySigned)<div class="alert alert-success">Signature completed on {{ $alreadySigned->timezone('Asia/Dubai')->format('d M Y, h:i A') }} GST.</div>@if($cancellation->completed_at)<a class="btn btn-dark w-100" target="_blank" href="{{ route('unit-cancellations.pdf', $party === 'owner' ? $cancellation->owner_token : $cancellation->company_token) }}">Open Final Signed PDF</a>@endif
@else<form method="POST" action="{{ route('unit-cancellations.sign', $party === 'owner' ? $cancellation->owner_token : $cancellation->company_token) }}" id="signForm">@csrf
<div class="notice mb-3">Review the complete document. Sign inside the large box using a mouse, finger, or stylus.</div>
<label class="form-label" for="signed_by_name">Full legal name</label><input id="signed_by_name" name="signed_by_name" class="form-control form-control-lg mb-3" value="{{ old('signed_by_name', $party === 'owner' ? $cancellation->owner_name : $cancellation->company_signer_name) }}" required>
<label class="form-label">Draw signature</label><canvas class="signature-canvas" id="signatureCanvas"></canvas><input type="hidden" name="signature_data" id="signatureData">
<div class="form-check mt-3"><input class="form-check-input" type="checkbox" value="1" name="accepted" id="accepted" required><label class="form-check-label" for="accepted">I have read this document and voluntarily agree to sign it electronically.</label></div>
<div class="d-flex gap-2 mt-4"><button type="button" class="btn btn-light btn-lg w-50" id="clearSignature">Clear</button><button class="btn btn-primary btn-lg w-50">Sign Document</button></div>
</form>@endif
</div></div></div></div></main>
<script>const c=document.getElementById('signatureCanvas');if(c){const x=c.getContext('2d'),d=document.getElementById('signatureData');let draw=false,ink=false;function size(){const r=c.getBoundingClientRect(),ratio=window.devicePixelRatio||1;c.width=r.width*ratio;c.height=r.height*ratio;x.setTransform(ratio,0,0,ratio,0,0);x.lineWidth=3;x.lineCap='round';x.strokeStyle='#14233b'}function p(e){const r=c.getBoundingClientRect(),s=e.touches?e.touches[0]:e;return{x:s.clientX-r.left,y:s.clientY-r.top}}function start(e){draw=ink=true;const q=p(e);x.beginPath();x.moveTo(q.x,q.y);e.preventDefault()}function move(e){if(!draw)return;const q=p(e);x.lineTo(q.x,q.y);x.stroke();e.preventDefault()}function end(){if(!draw)return;draw=false;d.value=c.toDataURL('image/png')}size();c.addEventListener('mousedown',start);c.addEventListener('mousemove',move);window.addEventListener('mouseup',end);c.addEventListener('touchstart',start,{passive:false});c.addEventListener('touchmove',move,{passive:false});c.addEventListener('touchend',end);document.getElementById('clearSignature').onclick=()=>{x.clearRect(0,0,c.width,c.height);ink=false;d.value=''};document.getElementById('signForm').onsubmit=e=>{if(!ink||!d.value){e.preventDefault();alert('Please draw your signature in the box.')}}}</script></body></html>
