<?php

namespace App\Support;

class CountryOptions
{
    public static function all(): array
    {
        return [
            ['iso' => 'AF', 'name' => 'Afghanistan', 'nationality' => 'Afghan', 'dial' => '+93'],
            ['iso' => 'AL', 'name' => 'Albania', 'nationality' => 'Albanian', 'dial' => '+355'],
            ['iso' => 'DZ', 'name' => 'Algeria', 'nationality' => 'Algerian', 'dial' => '+213'],
            ['iso' => 'AD', 'name' => 'Andorra', 'nationality' => 'Andorran', 'dial' => '+376'],
            ['iso' => 'AO', 'name' => 'Angola', 'nationality' => 'Angolan', 'dial' => '+244'],
            ['iso' => 'AG', 'name' => 'Antigua and Barbuda', 'nationality' => 'Antiguan or Barbudan', 'dial' => '+1268'],
            ['iso' => 'AR', 'name' => 'Argentina', 'nationality' => 'Argentine', 'dial' => '+54'],
            ['iso' => 'AM', 'name' => 'Armenia', 'nationality' => 'Armenian', 'dial' => '+374'],
            ['iso' => 'AU', 'name' => 'Australia', 'nationality' => 'Australian', 'dial' => '+61'],
            ['iso' => 'AT', 'name' => 'Austria', 'nationality' => 'Austrian', 'dial' => '+43'],
            ['iso' => 'AZ', 'name' => 'Azerbaijan', 'nationality' => 'Azerbaijani', 'dial' => '+994'],
            ['iso' => 'BS', 'name' => 'Bahamas', 'nationality' => 'Bahamian', 'dial' => '+1242'],
            ['iso' => 'BH', 'name' => 'Bahrain', 'nationality' => 'Bahraini', 'dial' => '+973'],
            ['iso' => 'BD', 'name' => 'Bangladesh', 'nationality' => 'Bangladeshi', 'dial' => '+880'],
            ['iso' => 'BB', 'name' => 'Barbados', 'nationality' => 'Barbadian', 'dial' => '+1246'],
            ['iso' => 'BY', 'name' => 'Belarus', 'nationality' => 'Belarusian', 'dial' => '+375'],
            ['iso' => 'BE', 'name' => 'Belgium', 'nationality' => 'Belgian', 'dial' => '+32'],
            ['iso' => 'BZ', 'name' => 'Belize', 'nationality' => 'Belizean', 'dial' => '+501'],
            ['iso' => 'BJ', 'name' => 'Benin', 'nationality' => 'Beninese', 'dial' => '+229'],
            ['iso' => 'BT', 'name' => 'Bhutan', 'nationality' => 'Bhutanese', 'dial' => '+975'],
            ['iso' => 'BO', 'name' => 'Bolivia', 'nationality' => 'Bolivian', 'dial' => '+591'],
            ['iso' => 'BA', 'name' => 'Bosnia and Herzegovina', 'nationality' => 'Bosnian or Herzegovinian', 'dial' => '+387'],
            ['iso' => 'BW', 'name' => 'Botswana', 'nationality' => 'Motswana', 'dial' => '+267'],
            ['iso' => 'BR', 'name' => 'Brazil', 'nationality' => 'Brazilian', 'dial' => '+55'],
            ['iso' => 'BN', 'name' => 'Brunei', 'nationality' => 'Bruneian', 'dial' => '+673'],
            ['iso' => 'BG', 'name' => 'Bulgaria', 'nationality' => 'Bulgarian', 'dial' => '+359'],
            ['iso' => 'BF', 'name' => 'Burkina Faso', 'nationality' => 'Burkinabe', 'dial' => '+226'],
            ['iso' => 'BI', 'name' => 'Burundi', 'nationality' => 'Burundian', 'dial' => '+257'],
            ['iso' => 'KH', 'name' => 'Cambodia', 'nationality' => 'Cambodian', 'dial' => '+855'],
            ['iso' => 'CM', 'name' => 'Cameroon', 'nationality' => 'Cameroonian', 'dial' => '+237'],
            ['iso' => 'CA', 'name' => 'Canada', 'nationality' => 'Canadian', 'dial' => '+1'],
            ['iso' => 'CV', 'name' => 'Cape Verde', 'nationality' => 'Cape Verdean', 'dial' => '+238'],
            ['iso' => 'CF', 'name' => 'Central African Republic', 'nationality' => 'Central African', 'dial' => '+236'],
            ['iso' => 'TD', 'name' => 'Chad', 'nationality' => 'Chadian', 'dial' => '+235'],
            ['iso' => 'CL', 'name' => 'Chile', 'nationality' => 'Chilean', 'dial' => '+56'],
            ['iso' => 'CN', 'name' => 'China', 'nationality' => 'Chinese', 'dial' => '+86'],
            ['iso' => 'CO', 'name' => 'Colombia', 'nationality' => 'Colombian', 'dial' => '+57'],
            ['iso' => 'KM', 'name' => 'Comoros', 'nationality' => 'Comoran', 'dial' => '+269'],
            ['iso' => 'CG', 'name' => 'Congo', 'nationality' => 'Congolese', 'dial' => '+242'],
            ['iso' => 'CD', 'name' => 'Democratic Republic of the Congo', 'nationality' => 'Congolese', 'dial' => '+243'],
            ['iso' => 'CR', 'name' => 'Costa Rica', 'nationality' => 'Costa Rican', 'dial' => '+506'],
            ['iso' => 'CI', 'name' => 'Cote dIvoire', 'nationality' => 'Ivorian', 'dial' => '+225'],
            ['iso' => 'HR', 'name' => 'Croatia', 'nationality' => 'Croatian', 'dial' => '+385'],
            ['iso' => 'CU', 'name' => 'Cuba', 'nationality' => 'Cuban', 'dial' => '+53'],
            ['iso' => 'CY', 'name' => 'Cyprus', 'nationality' => 'Cypriot', 'dial' => '+357'],
            ['iso' => 'CZ', 'name' => 'Czech Republic', 'nationality' => 'Czech', 'dial' => '+420'],
            ['iso' => 'DK', 'name' => 'Denmark', 'nationality' => 'Danish', 'dial' => '+45'],
            ['iso' => 'DJ', 'name' => 'Djibouti', 'nationality' => 'Djiboutian', 'dial' => '+253'],
            ['iso' => 'DM', 'name' => 'Dominica', 'nationality' => 'Dominican', 'dial' => '+1767'],
            ['iso' => 'DO', 'name' => 'Dominican Republic', 'nationality' => 'Dominican', 'dial' => '+1809'],
            ['iso' => 'EC', 'name' => 'Ecuador', 'nationality' => 'Ecuadorian', 'dial' => '+593'],
            ['iso' => 'EG', 'name' => 'Egypt', 'nationality' => 'Egyptian', 'dial' => '+20'],
            ['iso' => 'SV', 'name' => 'El Salvador', 'nationality' => 'Salvadoran', 'dial' => '+503'],
            ['iso' => 'GQ', 'name' => 'Equatorial Guinea', 'nationality' => 'Equatorial Guinean', 'dial' => '+240'],
            ['iso' => 'ER', 'name' => 'Eritrea', 'nationality' => 'Eritrean', 'dial' => '+291'],
            ['iso' => 'EE', 'name' => 'Estonia', 'nationality' => 'Estonian', 'dial' => '+372'],
            ['iso' => 'SZ', 'name' => 'Eswatini', 'nationality' => 'Swazi', 'dial' => '+268'],
            ['iso' => 'ET', 'name' => 'Ethiopia', 'nationality' => 'Ethiopian', 'dial' => '+251'],
            ['iso' => 'FJ', 'name' => 'Fiji', 'nationality' => 'Fijian', 'dial' => '+679'],
            ['iso' => 'FI', 'name' => 'Finland', 'nationality' => 'Finnish', 'dial' => '+358'],
            ['iso' => 'FR', 'name' => 'France', 'nationality' => 'French', 'dial' => '+33'],
            ['iso' => 'GA', 'name' => 'Gabon', 'nationality' => 'Gabonese', 'dial' => '+241'],
            ['iso' => 'GM', 'name' => 'Gambia', 'nationality' => 'Gambian', 'dial' => '+220'],
            ['iso' => 'GE', 'name' => 'Georgia', 'nationality' => 'Georgian', 'dial' => '+995'],
            ['iso' => 'DE', 'name' => 'Germany', 'nationality' => 'German', 'dial' => '+49'],
            ['iso' => 'GH', 'name' => 'Ghana', 'nationality' => 'Ghanaian', 'dial' => '+233'],
            ['iso' => 'GR', 'name' => 'Greece', 'nationality' => 'Greek', 'dial' => '+30'],
            ['iso' => 'GD', 'name' => 'Grenada', 'nationality' => 'Grenadian', 'dial' => '+1473'],
            ['iso' => 'GT', 'name' => 'Guatemala', 'nationality' => 'Guatemalan', 'dial' => '+502'],
            ['iso' => 'GN', 'name' => 'Guinea', 'nationality' => 'Guinean', 'dial' => '+224'],
            ['iso' => 'GW', 'name' => 'Guinea-Bissau', 'nationality' => 'Bissau-Guinean', 'dial' => '+245'],
            ['iso' => 'GY', 'name' => 'Guyana', 'nationality' => 'Guyanese', 'dial' => '+592'],
            ['iso' => 'HT', 'name' => 'Haiti', 'nationality' => 'Haitian', 'dial' => '+509'],
            ['iso' => 'HN', 'name' => 'Honduras', 'nationality' => 'Honduran', 'dial' => '+504'],
            ['iso' => 'HU', 'name' => 'Hungary', 'nationality' => 'Hungarian', 'dial' => '+36'],
            ['iso' => 'IS', 'name' => 'Iceland', 'nationality' => 'Icelandic', 'dial' => '+354'],
            ['iso' => 'IN', 'name' => 'India', 'nationality' => 'Indian', 'dial' => '+91'],
            ['iso' => 'ID', 'name' => 'Indonesia', 'nationality' => 'Indonesian', 'dial' => '+62'],
            ['iso' => 'IR', 'name' => 'Iran', 'nationality' => 'Iranian', 'dial' => '+98'],
            ['iso' => 'IQ', 'name' => 'Iraq', 'nationality' => 'Iraqi', 'dial' => '+964'],
            ['iso' => 'IE', 'name' => 'Ireland', 'nationality' => 'Irish', 'dial' => '+353'],
            ['iso' => 'IL', 'name' => 'Israel', 'nationality' => 'Israeli', 'dial' => '+972'],
            ['iso' => 'IT', 'name' => 'Italy', 'nationality' => 'Italian', 'dial' => '+39'],
            ['iso' => 'JM', 'name' => 'Jamaica', 'nationality' => 'Jamaican', 'dial' => '+1876'],
            ['iso' => 'JP', 'name' => 'Japan', 'nationality' => 'Japanese', 'dial' => '+81'],
            ['iso' => 'JO', 'name' => 'Jordan', 'nationality' => 'Jordanian', 'dial' => '+962'],
            ['iso' => 'KZ', 'name' => 'Kazakhstan', 'nationality' => 'Kazakhstani', 'dial' => '+7'],
            ['iso' => 'KE', 'name' => 'Kenya', 'nationality' => 'Kenyan', 'dial' => '+254'],
            ['iso' => 'KI', 'name' => 'Kiribati', 'nationality' => 'I-Kiribati', 'dial' => '+686'],
            ['iso' => 'KW', 'name' => 'Kuwait', 'nationality' => 'Kuwaiti', 'dial' => '+965'],
            ['iso' => 'KG', 'name' => 'Kyrgyzstan', 'nationality' => 'Kyrgyzstani', 'dial' => '+996'],
            ['iso' => 'LA', 'name' => 'Laos', 'nationality' => 'Lao', 'dial' => '+856'],
            ['iso' => 'LV', 'name' => 'Latvia', 'nationality' => 'Latvian', 'dial' => '+371'],
            ['iso' => 'LB', 'name' => 'Lebanon', 'nationality' => 'Lebanese', 'dial' => '+961'],
            ['iso' => 'LS', 'name' => 'Lesotho', 'nationality' => 'Basotho', 'dial' => '+266'],
            ['iso' => 'LR', 'name' => 'Liberia', 'nationality' => 'Liberian', 'dial' => '+231'],
            ['iso' => 'LY', 'name' => 'Libya', 'nationality' => 'Libyan', 'dial' => '+218'],
            ['iso' => 'LI', 'name' => 'Liechtenstein', 'nationality' => 'Liechtensteiner', 'dial' => '+423'],
            ['iso' => 'LT', 'name' => 'Lithuania', 'nationality' => 'Lithuanian', 'dial' => '+370'],
            ['iso' => 'LU', 'name' => 'Luxembourg', 'nationality' => 'Luxembourgish', 'dial' => '+352'],
            ['iso' => 'MG', 'name' => 'Madagascar', 'nationality' => 'Malagasy', 'dial' => '+261'],
            ['iso' => 'MW', 'name' => 'Malawi', 'nationality' => 'Malawian', 'dial' => '+265'],
            ['iso' => 'MY', 'name' => 'Malaysia', 'nationality' => 'Malaysian', 'dial' => '+60'],
            ['iso' => 'MV', 'name' => 'Maldives', 'nationality' => 'Maldivian', 'dial' => '+960'],
            ['iso' => 'ML', 'name' => 'Mali', 'nationality' => 'Malian', 'dial' => '+223'],
            ['iso' => 'MT', 'name' => 'Malta', 'nationality' => 'Maltese', 'dial' => '+356'],
            ['iso' => 'MH', 'name' => 'Marshall Islands', 'nationality' => 'Marshallese', 'dial' => '+692'],
            ['iso' => 'MR', 'name' => 'Mauritania', 'nationality' => 'Mauritanian', 'dial' => '+222'],
            ['iso' => 'MU', 'name' => 'Mauritius', 'nationality' => 'Mauritian', 'dial' => '+230'],
            ['iso' => 'MX', 'name' => 'Mexico', 'nationality' => 'Mexican', 'dial' => '+52'],
            ['iso' => 'FM', 'name' => 'Micronesia', 'nationality' => 'Micronesian', 'dial' => '+691'],
            ['iso' => 'MD', 'name' => 'Moldova', 'nationality' => 'Moldovan', 'dial' => '+373'],
            ['iso' => 'MC', 'name' => 'Monaco', 'nationality' => 'Monegasque', 'dial' => '+377'],
            ['iso' => 'MN', 'name' => 'Mongolia', 'nationality' => 'Mongolian', 'dial' => '+976'],
            ['iso' => 'ME', 'name' => 'Montenegro', 'nationality' => 'Montenegrin', 'dial' => '+382'],
            ['iso' => 'MA', 'name' => 'Morocco', 'nationality' => 'Moroccan', 'dial' => '+212'],
            ['iso' => 'MZ', 'name' => 'Mozambique', 'nationality' => 'Mozambican', 'dial' => '+258'],
            ['iso' => 'MM', 'name' => 'Myanmar', 'nationality' => 'Burmese', 'dial' => '+95'],
            ['iso' => 'NA', 'name' => 'Namibia', 'nationality' => 'Namibian', 'dial' => '+264'],
            ['iso' => 'NR', 'name' => 'Nauru', 'nationality' => 'Nauruan', 'dial' => '+674'],
            ['iso' => 'NP', 'name' => 'Nepal', 'nationality' => 'Nepalese', 'dial' => '+977'],
            ['iso' => 'NL', 'name' => 'Netherlands', 'nationality' => 'Dutch', 'dial' => '+31'],
            ['iso' => 'NZ', 'name' => 'New Zealand', 'nationality' => 'New Zealander', 'dial' => '+64'],
            ['iso' => 'NI', 'name' => 'Nicaragua', 'nationality' => 'Nicaraguan', 'dial' => '+505'],
            ['iso' => 'NE', 'name' => 'Niger', 'nationality' => 'Nigerien', 'dial' => '+227'],
            ['iso' => 'NG', 'name' => 'Nigeria', 'nationality' => 'Nigerian', 'dial' => '+234'],
            ['iso' => 'KP', 'name' => 'North Korea', 'nationality' => 'North Korean', 'dial' => '+850'],
            ['iso' => 'MK', 'name' => 'North Macedonia', 'nationality' => 'Macedonian', 'dial' => '+389'],
            ['iso' => 'NO', 'name' => 'Norway', 'nationality' => 'Norwegian', 'dial' => '+47'],
            ['iso' => 'OM', 'name' => 'Oman', 'nationality' => 'Omani', 'dial' => '+968'],
            ['iso' => 'PK', 'name' => 'Pakistan', 'nationality' => 'Pakistani', 'dial' => '+92'],
            ['iso' => 'PW', 'name' => 'Palau', 'nationality' => 'Palauan', 'dial' => '+680'],
            ['iso' => 'PS', 'name' => 'Palestine', 'nationality' => 'Palestinian', 'dial' => '+970'],
            ['iso' => 'PA', 'name' => 'Panama', 'nationality' => 'Panamanian', 'dial' => '+507'],
            ['iso' => 'PG', 'name' => 'Papua New Guinea', 'nationality' => 'Papua New Guinean', 'dial' => '+675'],
            ['iso' => 'PY', 'name' => 'Paraguay', 'nationality' => 'Paraguayan', 'dial' => '+595'],
            ['iso' => 'PE', 'name' => 'Peru', 'nationality' => 'Peruvian', 'dial' => '+51'],
            ['iso' => 'PH', 'name' => 'Philippines', 'nationality' => 'Filipino', 'dial' => '+63'],
            ['iso' => 'PL', 'name' => 'Poland', 'nationality' => 'Polish', 'dial' => '+48'],
            ['iso' => 'PT', 'name' => 'Portugal', 'nationality' => 'Portuguese', 'dial' => '+351'],
            ['iso' => 'QA', 'name' => 'Qatar', 'nationality' => 'Qatari', 'dial' => '+974'],
            ['iso' => 'RO', 'name' => 'Romania', 'nationality' => 'Romanian', 'dial' => '+40'],
            ['iso' => 'RU', 'name' => 'Russia', 'nationality' => 'Russian', 'dial' => '+7'],
            ['iso' => 'RW', 'name' => 'Rwanda', 'nationality' => 'Rwandan', 'dial' => '+250'],
            ['iso' => 'KN', 'name' => 'Saint Kitts and Nevis', 'nationality' => 'Kittitian or Nevisian', 'dial' => '+1869'],
            ['iso' => 'LC', 'name' => 'Saint Lucia', 'nationality' => 'Saint Lucian', 'dial' => '+1758'],
            ['iso' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'nationality' => 'Vincentian', 'dial' => '+1784'],
            ['iso' => 'WS', 'name' => 'Samoa', 'nationality' => 'Samoan', 'dial' => '+685'],
            ['iso' => 'SM', 'name' => 'San Marino', 'nationality' => 'Sammarinese', 'dial' => '+378'],
            ['iso' => 'ST', 'name' => 'Sao Tome and Principe', 'nationality' => 'Sao Tomean', 'dial' => '+239'],
            ['iso' => 'SA', 'name' => 'Saudi Arabia', 'nationality' => 'Saudi', 'dial' => '+966'],
            ['iso' => 'SN', 'name' => 'Senegal', 'nationality' => 'Senegalese', 'dial' => '+221'],
            ['iso' => 'RS', 'name' => 'Serbia', 'nationality' => 'Serbian', 'dial' => '+381'],
            ['iso' => 'SC', 'name' => 'Seychelles', 'nationality' => 'Seychellois', 'dial' => '+248'],
            ['iso' => 'SL', 'name' => 'Sierra Leone', 'nationality' => 'Sierra Leonean', 'dial' => '+232'],
            ['iso' => 'SG', 'name' => 'Singapore', 'nationality' => 'Singaporean', 'dial' => '+65'],
            ['iso' => 'SK', 'name' => 'Slovakia', 'nationality' => 'Slovak', 'dial' => '+421'],
            ['iso' => 'SI', 'name' => 'Slovenia', 'nationality' => 'Slovenian', 'dial' => '+386'],
            ['iso' => 'SB', 'name' => 'Solomon Islands', 'nationality' => 'Solomon Islander', 'dial' => '+677'],
            ['iso' => 'SO', 'name' => 'Somalia', 'nationality' => 'Somali', 'dial' => '+252'],
            ['iso' => 'ZA', 'name' => 'South Africa', 'nationality' => 'South African', 'dial' => '+27'],
            ['iso' => 'KR', 'name' => 'South Korea', 'nationality' => 'South Korean', 'dial' => '+82'],
            ['iso' => 'SS', 'name' => 'South Sudan', 'nationality' => 'South Sudanese', 'dial' => '+211'],
            ['iso' => 'ES', 'name' => 'Spain', 'nationality' => 'Spanish', 'dial' => '+34'],
            ['iso' => 'LK', 'name' => 'Sri Lanka', 'nationality' => 'Sri Lankan', 'dial' => '+94'],
            ['iso' => 'SD', 'name' => 'Sudan', 'nationality' => 'Sudanese', 'dial' => '+249'],
            ['iso' => 'SR', 'name' => 'Suriname', 'nationality' => 'Surinamese', 'dial' => '+597'],
            ['iso' => 'SE', 'name' => 'Sweden', 'nationality' => 'Swedish', 'dial' => '+46'],
            ['iso' => 'CH', 'name' => 'Switzerland', 'nationality' => 'Swiss', 'dial' => '+41'],
            ['iso' => 'SY', 'name' => 'Syria', 'nationality' => 'Syrian', 'dial' => '+963'],
            ['iso' => 'TW', 'name' => 'Taiwan', 'nationality' => 'Taiwanese', 'dial' => '+886'],
            ['iso' => 'TJ', 'name' => 'Tajikistan', 'nationality' => 'Tajikistani', 'dial' => '+992'],
            ['iso' => 'TZ', 'name' => 'Tanzania', 'nationality' => 'Tanzanian', 'dial' => '+255'],
            ['iso' => 'TH', 'name' => 'Thailand', 'nationality' => 'Thai', 'dial' => '+66'],
            ['iso' => 'TL', 'name' => 'Timor-Leste', 'nationality' => 'Timorese', 'dial' => '+670'],
            ['iso' => 'TG', 'name' => 'Togo', 'nationality' => 'Togolese', 'dial' => '+228'],
            ['iso' => 'TO', 'name' => 'Tonga', 'nationality' => 'Tongan', 'dial' => '+676'],
            ['iso' => 'TT', 'name' => 'Trinidad and Tobago', 'nationality' => 'Trinidadian or Tobagonian', 'dial' => '+1868'],
            ['iso' => 'TN', 'name' => 'Tunisia', 'nationality' => 'Tunisian', 'dial' => '+216'],
            ['iso' => 'TR', 'name' => 'Turkey', 'nationality' => 'Turkish', 'dial' => '+90'],
            ['iso' => 'TM', 'name' => 'Turkmenistan', 'nationality' => 'Turkmen', 'dial' => '+993'],
            ['iso' => 'TV', 'name' => 'Tuvalu', 'nationality' => 'Tuvaluan', 'dial' => '+688'],
            ['iso' => 'UG', 'name' => 'Uganda', 'nationality' => 'Ugandan', 'dial' => '+256'],
            ['iso' => 'UA', 'name' => 'Ukraine', 'nationality' => 'Ukrainian', 'dial' => '+380'],
            ['iso' => 'AE', 'name' => 'United Arab Emirates', 'nationality' => 'Emirati', 'dial' => '+971'],
            ['iso' => 'GB', 'name' => 'United Kingdom', 'nationality' => 'British', 'dial' => '+44'],
            ['iso' => 'US', 'name' => 'United States', 'nationality' => 'American', 'dial' => '+1'],
            ['iso' => 'UY', 'name' => 'Uruguay', 'nationality' => 'Uruguayan', 'dial' => '+598'],
            ['iso' => 'UZ', 'name' => 'Uzbekistan', 'nationality' => 'Uzbekistani', 'dial' => '+998'],
            ['iso' => 'VU', 'name' => 'Vanuatu', 'nationality' => 'Ni-Vanuatu', 'dial' => '+678'],
            ['iso' => 'VA', 'name' => 'Vatican City', 'nationality' => 'Vatican', 'dial' => '+379'],
            ['iso' => 'VE', 'name' => 'Venezuela', 'nationality' => 'Venezuelan', 'dial' => '+58'],
            ['iso' => 'VN', 'name' => 'Vietnam', 'nationality' => 'Vietnamese', 'dial' => '+84'],
            ['iso' => 'YE', 'name' => 'Yemen', 'nationality' => 'Yemeni', 'dial' => '+967'],
            ['iso' => 'ZM', 'name' => 'Zambia', 'nationality' => 'Zambian', 'dial' => '+260'],
            ['iso' => 'ZW', 'name' => 'Zimbabwe', 'nationality' => 'Zimbabwean', 'dial' => '+263'],
        ];
    }

    public static function nationalities(): array
    {
        $nationalities = array_values(array_unique(array_column(self::all(), 'nationality')));
        sort($nationalities);

        return $nationalities;
    }

    public static function flag(string $iso): string
    {
        $iso = strtoupper($iso);

        if (strlen($iso) !== 2 || ! function_exists('mb_chr')) {
            return $iso;
        }

        return mb_chr(127397 + ord($iso[0]), 'UTF-8') . mb_chr(127397 + ord($iso[1]), 'UTF-8');
    }

    public static function phoneLabel(array $country): string
    {
        return self::flag($country['iso']) . ' ' . $country['name'] . ' ' . $country['dial'];
    }
}
