@extends('layouts.owner-pwa')

@section('content')
@php
    $photoFor = function ($property) {
        $photos = is_array($property?->photos) ? $property->photos : json_decode($property?->photos ?: '[]', true);
        return !empty($photos) ? \App\Support\MediaStorage::url($photos[0]) : asset('assets/images/properties/p-1.jpg');
    };
    $statusClass = fn($status) => in_array($status, ['completed','paid','owner_paid','approved','confirmed'], true) ? '' : (in_array($status, ['pending','in_progress','outstanding'], true) ? 'warn' : 'info');
@endphp
<main class="owner-app" data-owner-app>
    <button class="oa-install" data-install><i class="ri-download-cloud-2-line"></i> Install Owner App</button>

    <section class="oa-screen" data-screen="home">
        <header class="oa-hero">
            <div class="oa-top"><div><div class="oa-sub">Good {{ now()->hour < 12 ? 'morning' : (now()->hour < 18 ? 'afternoon' : 'evening') }},</div><h1 class="oa-title">{{ Str::before($owner->name, ' ') }} <span class="gold">&#128075;</span></h1></div><button class="oa-icon-btn" data-go="notifications"><i class="ri-notification-3-line"></i></button></div>
            <div class="oa-grid three">
                <div class="oa-metric"><small>Gross revenue</small><strong class="green">AED {{ number_format($monthlyRevenue,0) }}</strong></div>
                <div class="oa-metric"><small>Expenses</small><strong class="red">AED {{ number_format($monthlyExpenses,0) }}</strong></div>
                <div class="oa-metric"><small>Management fee</small><strong class="gold">AED {{ number_format($managementFees,0) }}</strong></div>
            </div>
            <div class="oa-net"><small>Net payable</small><strong>AED {{ number_format($balance,0) }}</strong></div>
        </header>
        <div class="oa-grid three">
            <div class="oa-metric"><small>Properties</small><strong>{{ $properties->count() }}</strong></div><div class="oa-metric"><small>Bookings</small><strong>{{ $bookings->count() }}</strong></div><div class="oa-metric"><small>Occupancy</small><strong>{{ $occupancy }}%</strong></div>
        </div>
        <div class="oa-section-head"><h2>Quick access</h2></div>
        <div class="oa-actions"><a class="oa-action" data-go="calendar"><i class="ri-calendar-line"></i>Calendar</a><a class="oa-action" data-go="utilities"><i class="ri-flashlight-line"></i>Utilities</a><a class="oa-action" data-go="maintenance"><i class="ri-tools-line"></i>Maintenance</a><a class="oa-action" data-go="documents"><i class="ri-folder-3-line"></i>Documents</a></div>
        <div class="oa-section-head"><h2>Upcoming bookings</h2><a data-go="bookings">View all</a></div>
        <div class="oa-list">@forelse($bookings->where('check_out','>=',now())->take(3) as $booking)<a class="oa-row" data-go="booking-{{ $booking->id }}"><img class="oa-thumb" src="{{ $photoFor($booking->property) }}"><div class="oa-grow"><strong>{{ $booking->property?->name }}</strong><small>{{ $booking->check_in?->format('d M') }} - {{ $booking->check_out?->format('d M') }} | {{ $booking->guest_name }}</small></div><span class="oa-amount green">AED {{ number_format((float)$booking->rent_amount,0) }}</span></a>@empty<div class="oa-empty">No upcoming bookings</div>@endforelse</div>
    </section>

    <section class="oa-screen" data-screen="properties"><header class="oa-page-head"><h1>My Properties</h1><span class="oa-badge">{{ $properties->count() }} units</span></header><div class="oa-list">@forelse($properties as $property)<a class="oa-row" data-go="property-{{ $property->id }}"><img class="oa-thumb" src="{{ $photoFor($property) }}"><div class="oa-grow"><strong>{{ $property->building?->building_name ?? 'Property' }}</strong><small>{{ $property->name }} | {{ $property->unit_type_label }}</small><small class="green">{{ $property->status_label }}</small></div><i class="ri-arrow-right-s-line"></i></a>@empty<div class="oa-empty">No properties assigned</div>@endforelse</div></section>

    @foreach($properties as $property)
    <section class="oa-screen" data-screen="property-{{ $property->id }}"><div class="oa-photo" style="background-image:url('{{ $photoFor($property) }}')"></div><header class="oa-page-head"><button class="oa-back" data-go="properties"><i class="ri-arrow-left-line"></i></button><h1>{{ $property->name }}</h1><span class="oa-badge">{{ $property->status_label }}</span></header><div class="oa-card"><strong>{{ $property->building?->building_name }}</strong><p class="oa-sub">{{ $property->community ?: $property->building?->address }}</p><div class="oa-grid three"><div class="oa-metric"><small>Bedrooms</small><strong>{{ $property->bedrooms ?? '-' }}</strong></div><div class="oa-metric"><small>Bathrooms</small><strong>{{ $property->bathrooms ?? '-' }}</strong></div><div class="oa-metric"><small>Size</small><strong>{{ $property->square_foot ?? '-' }}</strong></div></div></div><div class="oa-actions"><a class="oa-action" data-go="calendar"><i class="ri-calendar-line"></i>Calendar</a><a class="oa-action" data-go="finance"><i class="ri-money-dollar-circle-line"></i>Finance</a><a class="oa-action" data-go="utilities"><i class="ri-flashlight-line"></i>Utilities</a><a class="oa-action" data-go="maintenance"><i class="ri-tools-line"></i>Maintenance</a></div><div class="oa-section-head"><h2>Performance</h2></div><div class="oa-card"><table class="oa-table"><tr><td>Revenue</td><td class="green">AED {{ number_format((float)$bookings->where('property_id',$property->id)->sum('rent_amount'),0) }}</td></tr><tr><td>Owner expenses</td><td class="red">AED {{ number_format((float)$expenses->where('property_id',$property->id)->sum('gross_amount'),0) }}</td></tr><tr><td>Bookings</td><td>{{ $bookings->where('property_id',$property->id)->count() }}</td></tr></table></div></section>
    @endforeach

    <section class="oa-screen" data-screen="bookings"><header class="oa-page-head"><h1>Bookings</h1><button class="oa-icon-btn" data-go="calendar"><i class="ri-calendar-line"></i></button></header><div class="oa-list">@forelse($bookings as $booking)<a class="oa-row" data-go="booking-{{ $booking->id }}"><img class="oa-thumb" src="{{ $photoFor($booking->property) }}"><div class="oa-grow"><strong>{{ $booking->booking_reference }}</strong><small>{{ $booking->property?->name }} | {{ $booking->guest_name }}</small><small>{{ $booking->check_in?->format('d M Y') }} - {{ $booking->check_out?->format('d M Y') }}</small></div><span class="oa-badge {{ $statusClass($booking->status) }}">{{ ucfirst($booking->status) }}</span></a>@empty<div class="oa-empty">No bookings found</div>@endforelse</div></section>

    @foreach($bookings as $booking)
    <section class="oa-screen" data-screen="booking-{{ $booking->id }}"><header class="oa-page-head"><button class="oa-back" data-go="bookings"><i class="ri-arrow-left-line"></i></button><h1>Booking Details</h1></header><div class="oa-row"><img class="oa-thumb" src="{{ $photoFor($booking->property) }}"><div class="oa-grow"><strong>{{ $booking->booking_reference }}</strong><small>{{ $booking->property?->name }}, {{ $booking->property?->building?->building_name }}</small></div><span class="oa-badge">{{ ucfirst($booking->status) }}</span></div><div class="oa-card"><table class="oa-table"><tr><td>Guest</td><td>{{ $booking->guest_name }}</td></tr><tr><td>Check-in</td><td>{{ $booking->check_in?->format('d M Y h:i A') }}</td></tr><tr><td>Check-out</td><td>{{ $booking->check_out?->format('d M Y h:i A') }}</td></tr><tr><td>Nights</td><td>{{ $booking->check_in?->diffInDays($booking->check_out) }}</td></tr><tr><td>Total</td><td>AED {{ number_format((float)$booking->rent_amount,2) }}</td></tr><tr><td>Payment</td><td class="green">{{ ucfirst($booking->invoice_status) }}</td></tr><tr><td>Source</td><td>{{ ucfirst($booking->source ?? '-') }}</td></tr></table></div></section>
    @endforeach

    <section class="oa-screen" data-screen="calendar"><header class="oa-page-head"><button class="oa-back" data-go="bookings"><i class="ri-arrow-left-line"></i></button><h1>{{ now()->format('F Y') }}</h1></header><div class="oa-card"><div class="oa-calendar">@foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $day)<span class="head">{{ $day }}</span>@endforeach @for($d=1;$d<=now()->daysInMonth;$d++)@php($date=now()->copy()->day($d))<span class="{{ $bookings->contains(fn($b)=>$date->between($b->check_in,$b->check_out))?'booked':'' }}">{{ $d }}</span>@endfor</div></div><div class="oa-section-head"><h2>Booking schedule</h2></div><div class="oa-list">@foreach($bookings->take(8) as $booking)<a class="oa-row" data-go="booking-{{ $booking->id }}"><div class="oa-grow"><strong>{{ $booking->property?->name }}</strong><small>{{ $booking->check_in?->format('d M') }} - {{ $booking->check_out?->format('d M') }}</small></div><span class="oa-amount green">AED {{ number_format((float)$booking->rent_amount,0) }}</span></a>@endforeach</div></section>

    <section class="oa-screen" data-screen="finance"><header class="oa-page-head"><h1>Finance</h1><span class="oa-sub">This month</span></header><div class="oa-finance"><small>Net payable</small><strong>AED {{ number_format($balance,2) }}</strong><button class="oa-statement" data-go="transactions">View Statement</button></div><div class="oa-card"><table class="oa-table"><tr><td>Gross revenue</td><td>AED {{ number_format($monthlyRevenue,2) }}</td></tr><tr><td>Expenses</td><td class="red">AED {{ number_format($monthlyExpenses,2) }}</td></tr><tr><td>Management fee</td><td>AED {{ number_format($managementFees,2) }}</td></tr><tr><td>Total credits</td><td class="green">AED {{ number_format($credits,2) }}</td></tr><tr><td>Total debits</td><td class="red">AED {{ number_format($debits,2) }}</td></tr></table></div><div class="oa-actions"><a class="oa-action" data-go="transactions"><i class="ri-exchange-dollar-line"></i>Transactions</a><a class="oa-action" data-go="payouts"><i class="ri-bank-line"></i>Payouts</a><a class="oa-action" data-go="utilities"><i class="ri-flashlight-line"></i>Utilities</a><a class="oa-action" data-go="documents"><i class="ri-file-list-3-line"></i>Statements</a></div></section>

    <section class="oa-screen" data-screen="transactions"><header class="oa-page-head"><button class="oa-back" data-go="finance"><i class="ri-arrow-left-line"></i></button><h1>Transactions</h1></header><div class="oa-list">@forelse($entries as $entry)<div class="oa-row"><div class="oa-grow"><strong>{{ $entry->type_label }}</strong><small>{{ $entry->entry_date?->format('d M Y') }} | {{ $entry->property?->name ?? 'All units' }}</small></div><span class="oa-amount {{ $entry->direction==='credit'?'green':'red' }}">{{ $entry->direction==='credit'?'+':'-' }} AED {{ number_format((float)$entry->amount,2) }}</span></div>@empty<div class="oa-empty">No transactions</div>@endforelse</div></section>

    <section class="oa-screen" data-screen="utilities"><header class="oa-page-head"><button class="oa-back" data-go="home"><i class="ri-arrow-left-line"></i></button><h1>Utilities</h1></header>@forelse($utilityBills->groupBy('property_id') as $propertyId=>$bills)<div class="oa-section-head"><h2>{{ $bills->first()->property?->name }}</h2></div><div class="oa-card"><table class="oa-table">@foreach($bills as $bill)<tr><td>{{ $bill->account?->type_label ?? ucfirst($bill->account?->utility_type ?? 'Utility') }}</td><td>AED {{ number_format((float)$bill->total_amount,2) }} <span class="oa-badge {{ $statusClass($bill->status) }}">{{ $bill->status_label }}</span></td></tr>@endforeach</table></div>@empty<div class="oa-empty">No utility bills</div>@endforelse</section>

    <section class="oa-screen" data-screen="maintenance"><header class="oa-page-head"><button class="oa-back" data-go="home"><i class="ri-arrow-left-line"></i></button><h1>Maintenance</h1></header><div class="oa-tabs" data-filter-group><button class="is-active" data-filter="all">All</button><button data-filter="in_progress">In progress</button><button data-filter="completed">Completed</button></div><div class="oa-list">@forelse($tasks as $task)<div class="oa-row" data-status="{{ $task->status }}"><div class="oa-grow"><strong>{{ $task->title }}</strong><small>{{ $task->property?->name ?? $task->booking?->property?->name }} | {{ $task->created_at?->format('d M Y') }}</small></div><span class="oa-badge {{ $statusClass($task->status) }}">{{ ucfirst(str_replace('_',' ',$task->status)) }}</span></div>@empty<div class="oa-empty">No maintenance tasks</div>@endforelse</div></section>

    <section class="oa-screen" data-screen="documents"><header class="oa-page-head"><button class="oa-back" data-go="home"><i class="ri-arrow-left-line"></i></button><h1>Document Wallet</h1></header><div class="oa-doc-grid">@foreach($unitDocuments as $document)<a class="oa-doc" href="{{ \App\Support\MediaStorage::url($document->file_path) }}" target="_blank"><i class="ri-folder-shield-2-line"></i><strong>{{ $document->title }}</strong><small>{{ $document->property?->name }} · {{ $document->expires_at?->format('d M Y') ?? 'No expiry' }}</small><span class="oa-badge {{ $statusClass($document->expiry_status) }}">{{ str($document->expiry_status)->headline() }}</span></a>@endforeach @forelse($documents as $document)<a class="oa-doc" href="{{ route('owner-documents.pdf',$document->signing_token) }}" target="_blank"><i class="ri-file-pdf-2-line"></i><strong>{{ $document->title }}</strong><small>{{ $document->property?->name }} · {{ $document->status_label }}</small></a>@empty @if($unitDocuments->isEmpty())<div class="oa-empty">No documents</div>@endif @endforelse</div></section>

    <section class="oa-screen" data-screen="notifications"><header class="oa-page-head"><button class="oa-back" data-go="home"><i class="ri-arrow-left-line"></i></button><h1>Notifications</h1></header><div class="oa-list">@forelse($notifications as $notification)<div class="oa-row"><i class="ri-notification-3-line gold"></i><div class="oa-grow"><strong>{{ data_get($notification->data,'title','Account update') }}</strong><small>{{ data_get($notification->data,'message','You have a new notification.') }}</small></div><small>{{ $notification->created_at?->diffForHumans() }}</small></div>@empty<div class="oa-empty">You are all caught up</div>@endforelse</div></section>

    <section class="oa-screen" data-screen="payouts"><header class="oa-page-head"><button class="oa-back" data-go="finance"><i class="ri-arrow-left-line"></i></button><h1>Payouts</h1></header><div class="oa-list">@forelse($payouts as $payout)<div class="oa-card"><div class="oa-top"><strong>{{ $payout->entry_date?->format('F Y') }} Payout</strong><span class="oa-badge">Paid</span></div><div class="oa-net"><small>Payout</small><strong>AED {{ number_format((float)$payout->amount,2) }}</strong></div><small>{{ $payout->reference }} | {{ $payout->description }}</small></div>@empty<div class="oa-empty">No payouts recorded</div>@endforelse</div></section>

    <section class="oa-screen" data-screen="profile"><header class="oa-hero oa-profile"><img class="oa-avatar" src="{{ \App\Support\MediaStorage::url($owner->profile_photo) ?: asset('assets/images/users/dummy-avatar.jpg') }}"><h1 class="oa-title">{{ $owner->name }}</h1><div class="oa-sub">Owner</div></header><div class="oa-card oa-menu"><button type="button" class="oa-menu-button" data-language-toggle><i class="ri-global-line"></i><span data-language-label>العربية</span><i class="ri-translate-2"></i></button><a href="{{ route('landlord.dashboard') }}"><i class="ri-computer-line"></i><span>Desktop Owner Portal</span><i class="ri-arrow-right-s-line"></i></a><a><i class="ri-user-line"></i><span>My Information</span><i class="ri-arrow-right-s-line"></i></a><a><i class="ri-bank-card-line"></i><span>Bank Details</span><i class="ri-arrow-right-s-line"></i></a><a data-go="change-password"><i class="ri-lock-password-line"></i><span>Change Password</span><i class="ri-arrow-right-s-line"></i></a><a data-go="documents"><i class="ri-folder-line"></i><span>My Documents</span><i class="ri-arrow-right-s-line"></i></a><a data-go="notifications"><i class="ri-notification-line"></i><span>Notifications</span><i class="ri-arrow-right-s-line"></i></a></div><form method="POST" action="{{ route('logout') }}">@csrf<button class="oa-statement red" style="border-color:#f0b9bf;background:#fff">Logout</button></form></section>

    <section class="oa-screen" data-screen="change-password"><header class="oa-page-head"><button class="oa-back" data-go="profile"><i class="ri-arrow-left-line"></i></button><h1>Change Password</h1></header>@if(session('status') === 'password-updated')<div class="oa-card green">Password updated successfully.</div>@endif<form class="oa-card oa-form" method="POST" action="{{ route('password.update') }}">@csrf @method('PUT')<label>Current Password<input type="password" name="current_password" autocomplete="current-password" required></label>@error('current_password','updatePassword')<small class="red">{{ $message }}</small>@enderror<label>New Password<input type="password" name="password" autocomplete="new-password" required></label>@error('password','updatePassword')<small class="red">{{ $message }}</small>@enderror<label>Confirm Password<input type="password" name="password_confirmation" autocomplete="new-password" required></label><button class="oa-primary" type="submit">Update Password</button></form></section>

    <nav class="oa-nav"><a data-nav="home" data-go="home"><i class="ri-home-5-line"></i>Home</a><a data-nav="properties" data-go="properties"><i class="ri-building-line"></i>Properties</a><a data-nav="bookings" data-go="bookings"><i class="ri-calendar-check-line"></i>Bookings</a><a data-nav="finance" data-go="finance"><i class="ri-wallet-3-line"></i>Finance</a><a data-nav="profile" data-go="profile"><i class="ri-user-3-line"></i>Profile</a></nav>
</main>
@endsection
