<!doctype html><html><head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;font-size:11px;color:#182c49}h1{font-size:22px}table{width:100%;border-collapse:collapse;margin-top:18px}td,th{padding:8px;border:1px solid #dde2eb;text-align:left}th{background:#eef1f8}.amount{text-align:right}.muted{color:#667085}
</style></head><body>
<h1>PAYMENT RECEIPT</h1>
<strong>{{ \App\Support\AppSettings::get('invoice_establishment_name') }}</strong><br>
{{ \App\Support\AppSettings::get('invoice_legal_name') }}<br>
{{ \App\Support\AppSettings::get('invoice_address') }}<br>TRN: {{ \App\Support\AppSettings::get('invoice_trn') }}
<p>Receipt summary for invoice: <strong>{{ $invoice->invoice_number }}</strong><br>
Booking: {{ $invoice->booking?->booking_reference }}<br>Received from: {{ $invoice->booking?->guest_name }}<br>
Unit: {{ $invoice->booking?->property?->building?->name }} — {{ $invoice->booking?->property?->name }}</p>
<table><thead><tr><th>Payment ID</th><th>Date</th><th>Method / Reference</th><th class="amount">Amount paid (AED)</th></tr></thead><tbody>
@foreach($invoice->payments->sortBy('payment_date') as $payment)
<tr><td>{{ $payment->id }}</td><td>{{ $payment->payment_date?->format('d M Y') }}</td><td>{{ $payment->payment_method }}<br>{{ $payment->reference }}</td><td class="amount">{{ number_format((float)$payment->amount,2) }}</td></tr>
@endforeach
<tr><th colspan="3">Total actually received</th><th class="amount">{{ number_format((float)$invoice->payments->sum('amount'),2) }}</th></tr>
<tr><td colspan="3">Invoice total</td><td class="amount">{{ number_format((float)$invoice->total_amount,2) }}</td></tr>
<tr><td colspan="3">Remaining invoice balance</td><td class="amount">{{ number_format($invoice->balance_due,2) }}</td></tr>
</tbody></table><p class="muted">This is evidence of recorded payments, not a tax invoice. Generated by system {{ now()->format('d M Y H:i') }}.</p>
</body></html>
